### ISSUE TITLE
Backend shuts down with "ImportError"

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-backend#1092]
The current image cannot build.

to reproduce:
```
make stop dev
make run dev
```
in OpenSlides4 master

used commit:
c7891fdc3688cb730c7d5819b7ded5a104e364be

error log:
```
[2021-12-09 15:24:55 +0000] [167] [INFO] Starting gunicorn 20.1.0
[2021-12-09 15:24:55 +0000] [168] [INFO] Starting gunicorn 20.1.0
[2021-12-09 15:24:55 +0000] [167] [DEBUG] Arbiter booted
[2021-12-09 15:24:55 +0000] [167] [INFO] Listening at: http://0.0.0.0:9002 (167)
[2021-12-09 15:24:55 +0000] [168] [DEBUG] Arbiter booted
[2021-12-09 15:24:55 +0000] [167] [INFO] Using worker: sync
[2021-12-09 15:24:55 +0000] [168] [INFO] Listening at: http://0.0.0.0:9003 (168)
[2021-12-09 15:24:55 +0000] [168] [INFO] Using worker: sync
[2021-12-09 15:24:55 +0000] [168] [DEBUG] 1 workers
[2021-12-09 15:24:55 +0000] [167] [DEBUG] 1 workers
[2021-12-09 15:24:55 +0000] [191] [INFO] Booting worker with pid: 191
[2021-12-09 15:24:55 +0000] [192] [INFO] Booting worker with pid: 192
[2021-12-09 15:24:57 +0000] [191] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/app/openslides_backend/main.py", line 63, in load
    from .wsgi import create_wsgi_application
  File "/app/openslides_backend/wsgi.py", line 7, in <module>
    from .http.views import ActionView, PresenterView
  File "/app/openslides_backend/http/views/__init__.py", line 1, in <module>
    from .action_view import ActionView  # noqa
  File "/app/openslides_backend/http/views/action_view.py", line 4, in <module>
    from ...migrations import assert_migration_index
  File "/app/openslides_backend/migrations/__init__.py", line 1, in <module>
    from migrations import InvalidMigrationsException
  File "openslides_backend/migrations/__init__.py", line 1, in <module>
    from migrations import InvalidMigrationsException
ImportError: cannot import name 'InvalidMigrationsException' from partially initialized module 'migrations' (most likely due to a circular import) (openslides_backend/migrations/__init__.py)
[2021-12-09 15:24:57 +0000] [192] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/app/openslides_backend/main.py", line 63, in load
    from .wsgi import create_wsgi_application
  File "/app/openslides_backend/wsgi.py", line 7, in <module>
    from .http.views import ActionView, PresenterView
  File "/app/openslides_backend/http/views/__init__.py", line 1, in <module>
    from .action_view import ActionView  # noqa
  File "/app/openslides_backend/http/views/action_view.py", line 4, in <module>
    from ...migrations import assert_migration_index
  File "/app/openslides_backend/migrations/__init__.py", line 1, in <module>
    from migrations import InvalidMigrationsException
  File "openslides_backend/migrations/__init__.py", line 1, in <module>
    from migrations import InvalidMigrationsException
ImportError: cannot import name 'InvalidMigrationsException' from partially initialized module 'migrations' (most likely due to a circular import) (openslides_backend/migrations/__init__.py)
[2021-12-09 15:24:58 +0000] [191] [INFO] Worker exiting (pid: 191)
[2021-12-09 15:24:58 +0000] [192] [INFO] Worker exiting (pid: 192)
[2021-12-09 15:24:58 +0000] [167] [INFO] Shutting down: Master
[2021-12-09 15:24:58 +0000] [167] [INFO] Reason: Worker failed to boot.
[2021-12-09 15:24:58 +0000] [168] [INFO] Shutting down: Master
[2021-12-09 15:24:58 +0000] [168] [INFO] Reason: Worker failed to boot.
Component action terminated. Terminate all other components now.
Parent process terminated.
```

**Comment by tsiegleauq** [comment]
Last working commit:
a2f1df276dc769067b764ba05f3450dbd01c2268

**Comment by jsangmeister** [comment]
Interesting, especially that this does not happen in the backend-only dev setup. Renaming the folder `openslides_backend/migrations` does fix it though, which is probably the easiest fix, although I'm not really a fan of this. The better approach would probably be to investigate why this name clash happens and why it only happens in the "full" setup, but I don't know if the time investment is worth it here. Maybe you can discuss this on monday if it's urgent and, if needed, implement this fix. Otherwise we can also talk about it on wednesday.
