### ISSUE TITLE
Internal Server Error on `meeting.clone` 

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#1182]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/app/openslides_backend/http/application.py", line 92, in __call__
    return self.wsgi_application(environ, start_response)
  File "/app/openslides_backend/http/application.py", line 82, in wsgi_application
    response = self.dispatch_request(request)
  File "/app/openslides_backend/http/application.py", line 44, in dispatch_request
    response_body, access_token = view_instance.dispatch(request)
  File "/app/openslides_backend/http/views/base_view.py", line 111, in dispatch
    return func(request)
  File "/app/openslides_backend/http/views/presenter_view.py", line 26, in presenter_route
    presenter_response, access_token = handler.handle_request(request)
  File "/app/openslides_backend/presenter/presenter.py", line 77, in handle_request
    response, access_token = self.parse_presenters(request)
  File "/app/openslides_backend/presenter/presenter.py", line 134, in parse_presenters
    result = presenter_instance.get_result()
  File "/app/openslides_backend/presenter/check_mediafile_id.py", line 48, in get_result
    self.check_permissions()
  File "/app/openslides_backend/presenter/check_mediafile_id.py", line 78, in check_permissions
    can_see_meeting = self.check_can_see_meeting(meeting)
  File "/app/openslides_backend/presenter/check_mediafile_id.py", line 128, in check_can_see_meeting
    meeting["committe_id"],
KeyError: 'committe_id'
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/app/openslides_backend/http/application.py", line 92, in __call__
    return self.wsgi_application(environ, start_response)
  File "/app/openslides_backend/http/application.py", line 82, in wsgi_application
    response = self.dispatch_request(request)
  File "/app/openslides_backend/http/application.py", line 44, in dispatch_request
    response_body, access_token = view_instance.dispatch(request)
  File "/app/openslides_backend/http/views/base_view.py", line 111, in dispatch
    return func(request)
  File "/app/openslides_backend/http/views/action_view.py", line 38, in action_route
    response = handler.handle_request(request.json, user_id, is_atomic)
  File "/app/openslides_backend/action/action_handler.py", line 112, in handle_request
    results = self.execute_write_requests(self.parse_actions, payload)
  File "/app/openslides_backend/action/action_handler.py", line 149, in execute_write_requests
    write_requests, data = get_write_requests(*args)
  File "/app/openslides_backend/action/action_handler.py", line 186, in parse_actions
    write_request, results = self.perform_action(element, relation_manager)
  File "/app/openslides_backend/action/action_handler.py", line 223, in perform_action
    write_request, results = action.perform(
  File "/app/openslides_backend/action/actions/meeting/import_.py", line 65, in perform
    instance = self.base_update_instance(instance)
  File "/app/openslides_backend/action/action.py", line 293, in base_update_instance
    return self.update_instance(instance)
  File "/app/openslides_backend/action/actions/meeting/clone.py", line 81, in update_instance
    checker.run_check()
  File "/app/openslides_backend/models/checker.py", line 317, in run_check
    self.check_model(collection, model)
  File "/app/openslides_backend/models/checker.py", line 340, in check_model
    errors = self.check_normal_fields(model, collection)
  File "/app/openslides_backend/models/checker.py", line 384, in check_normal_fields
    field.validate(model[fieldname], model)
  File "/app/openslides_backend/models/fields.py", line 469, in validate
    raise NotImplementedError
NotImplementedError
```

**Comment by reiterl** [comment]
The first one seems to be a typo in the meeting key.

**Comment by reiterl** [comment]
Add https://github.com/OpenSlides/openslides-backend/pull/1183 for the first problem.

**Comment by GabrielInTheWorld** [comment]
One additional thing:

```
Error: Uncaught (in promise): Error: 	motion/10: Invalid fields workflow_id (value: 7)
	mediafile/4: is_public is wrong. True != None
Error: 	motion/10: Invalid fields workflow_id (value: 7)
	mediafile/4: is_public is wrong. True != None
```

**Comment by GabrielInTheWorld** [comment]
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
>     self.handle_request(listener, req, client, addr)
>   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
>     respiter = self.wsgi(environ, resp.start_response)
>   File "/app/openslides_backend/http/application.py", line 92, in __call__
>     return self.wsgi_application(environ, start_response)
>   File "/app/openslides_backend/http/application.py", line 82, in wsgi_application
>     response = self.dispatch_request(request)
>   File "/app/openslides_backend/http/application.py", line 44, in dispatch_request
>     response_body, access_token = view_instance.dispatch(request)
>   File "/app/openslides_backend/http/views/base_view.py", line 111, in dispatch
>     return func(request)
>   File "/app/openslides_backend/http/views/action_view.py", line 38, in action_route
>     response = handler.handle_request(request.json, user_id, is_atomic)
>   File "/app/openslides_backend/action/action_handler.py", line 112, in handle_request
>     results = self.execute_write_requests(self.parse_actions, payload)
>   File "/app/openslides_backend/action/action_handler.py", line 149, in execute_write_requests
>     write_requests, data = get_write_requests(*args)
>   File "/app/openslides_backend/action/action_handler.py", line 186, in parse_actions
>     write_request, results = self.perform_action(element, relation_manager)
>   File "/app/openslides_backend/action/action_handler.py", line 223, in perform_action
>     write_request, results = action.perform(
>   File "/app/openslides_backend/action/actions/meeting/import_.py", line 65, in perform
>     instance = self.base_update_instance(instance)
>   File "/app/openslides_backend/action/action.py", line 293, in base_update_instance
>     return self.update_instance(instance)
>   File "/app/openslides_backend/action/actions/meeting/clone.py", line 81, in update_instance
>     checker.run_check()
>   File "/app/openslides_backend/models/checker.py", line 317, in run_check
>     self.check_model(collection, model)
>   File "/app/openslides_backend/models/checker.py", line 340, in check_model
>     errors = self.check_normal_fields(model, collection)
>   File "/app/openslides_backend/models/checker.py", line 384, in check_normal_fields
>     field.validate(model[fieldname], model)
>   File "/app/openslides_backend/models/fields.py", line 469, in validate
>     raise NotImplementedError
> NotImplementedError
> ```

It could be this snippet (in `models/fields.py`):
```python
class TemplateHTMLStrictField(BaseTemplateField, HTMLStrictField):
    def validate(self, value: Any, payload: Dict[str, Any] = {}) -> Any:
        if type(value) == dict:
            sup: Any = super()
            return {key: sup.validate(struc) for key, struc in value.items()}
        elif type(value) == list:
            return value
        elif value is None:
            return None
        raise NotImplementedError()
```

**Comment by reiterl** [comment]
> One additional thing:
> 
> ```
> Error: Uncaught (in promise): Error: 	motion/10: Invalid fields workflow_id (value: 7)
> 	mediafile/4: is_public is wrong. True != None
> Error: 	motion/10: Invalid fields workflow_id (value: 7)
> 	mediafile/4: is_public is wrong. True != None
> ```

Why does the motion/10 have the field workflow_id? I looked at the motion model. There is no field "workflow_id". So the data in the event store seems to be corrupt. The mediafile messages seems to be another problem.

**Comment by jsangmeister** [comment]
> Why does the motion/10 have the field workflow_id? I looked at the motion model. There is no field "workflow_id". So the data in the event store seems to be corrupt. The mediafile messages seems to be another problem.

Seems to stem from `motion.update`: https://github.com/OpenSlides/openslides-backend/blob/a32ee0a36cfcc9d4cb6695aa66595b2a74c2be61/openslides_backend/action/actions/motion/update.py#L83

A simple `pop` should however be enough to fix it here. Since this corruption breaks `meeting.clone`, it seems like we also need a migration which removes the corrupt fields.

**Comment by reiterl** [comment]
Add a pr https://github.com/OpenSlides/openslides-backend/pull/1209 for a fix of the workflow_id problem.

**Comment by GabrielInTheWorld** [comment]
Closing in favor of #1215 and #1228.
