### ISSUE TITLE
OS3 import error: AttributeError: 'list' object has no attribute 'values'

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-backend#1197]
Import OS3 export file of OS3 demo (demo.openslides.org).
Error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/app/openslides_backend/http/application.py", line 92, in __call__
    return self.wsgi_application(environ, start_response)
  File "/app/openslides_backend/http/application.py", line 82, in wsgi_application
    response = self.dispatch_request(request)
  File "/app/openslides_backend/http/application.py", line 44, in dispatch_request
    response_body, access_token = view_instance.dispatch(request)
  File "/app/openslides_backend/http/views/base_view.py", line 111, in dispatch
    return func(request)
  File "/app/openslides_backend/http/views/action_view.py", line 38, in action_route
    response = handler.handle_request(request.json, user_id, is_atomic)
  File "/app/openslides_backend/action/action_handler.py", line 112, in handle_request
    results = self.execute_write_requests(self.parse_actions, payload)
  File "/app/openslides_backend/action/action_handler.py", line 149, in execute_write_requests
    write_requests, data = get_write_requests(*args)
  File "/app/openslides_backend/action/action_handler.py", line 186, in parse_actions
    write_request, results = self.perform_action(element, relation_manager)
  File "/app/openslides_backend/action/action_handler.py", line 223, in perform_action
    write_request, results = action.perform(
  File "/app/openslides_backend/action/actions/meeting/import_.py", line 65, in perform
    instance = self.base_update_instance(instance)
  File "/app/openslides_backend/action/action.py", line 291, in base_update_instance
    return self.update_instance(instance)
  File "/app/openslides_backend/action/actions/meeting/import_.py", line 75, in update_instance
    if not len(meeting_json.get("meeting", {}).values()) == 1:
AttributeError: 'list' object has no attribute 'values'
```

**Comment by emanuelschuetze** [comment]
Right, the os3 demo is outdated (2021-10-07). I'll update it and try again. Here closed.
