### ISSUE TITLE
Investigate nonsensical error when attempting to delete structure_level

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#1347]
Got the following error from the backend when attempting to delete a previously set meeting-based structure_level of a participant who also had a default_structure_level on the organization level.
Couldn't replicate the same error a second time, no matter how often I tried reproducing the action, meaning that this may not be reproducible, so this issue is just to document the bug, in case anyone wants to investigate this.

Payload:
[
  {
    "action": "user.set_present",
    "data": [
      {
        "id": 23,
        "meeting_id": 4,
        "present": false
      }
    ]
  },
  {
    "action": "user.update",
    "data": [
      {
        "id": 23,
        "first_name": "Voll",
        "last_name": "Idiot",
        "username": "vollidiot",
        "is_physical_person": true,
        "default_password": "H2V3TTJhQz",
        "email": "",
        "group_$_ids": {
          "4": [
            16
          ]
        },
        "structure_level_$": {
          "4": ""
        },
        "number_$": {},
        "vote_weight_$": {
          "4": "1.000000"
        },
        "vote_delegated_$_to_id": {
          "4": null
        },
        "vote_delegations_$_from_ids": {
          "4": null
        }
      }
    ]
  }
]

Error msg:
<html> <head> <title>Internal Server Error</title> </head> <body> <h1><p>Internal Server Error</p></h1> </body> </html> 

Error-stack:
[2022-06-01 11:27:14 +0000] [50] [ERROR] Error handling request /system/action/handle_request
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
backend_1           |     self.handle_request(listener, req, client, addr)
backend_1           |   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
backend_1           |     respiter = self.wsgi(environ, resp.start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 92, in __call__
backend_1           |     return self.wsgi_application(environ, start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 82, in wsgi_application
backend_1           |     response = self.dispatch_request(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 44, in dispatch_request
backend_1           |     response_body, access_token = view_instance.dispatch(request)
backend_1           |   File "/app/openslides_backend/http/views/base_view.py", line 113, in dispatch
backend_1           |     return func(request)
backend_1           |   File "/app/openslides_backend/http/views/action_view.py", line 43, in action_route
backend_1           |     response = handler.handle_request(request.json, user_id, is_atomic)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 112, in handle_request
backend_1           |     results = self.execute_write_requests(self.parse_actions, payload)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 149, in execute_write_requests
backend_1           |     write_requests, data = get_write_requests(*args)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 186, in parse_actions
backend_1           |     write_request, results = self.perform_action(element, relation_manager)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 224, in perform_action
backend_1           |     write_request, results = action.perform(
backend_1           |   File "/app/openslides_backend/action/action.py", line 159, in perform
backend_1           |     instance = self.base_update_instance(instance)
backend_1           |   File "/app/openslides_backend/action/generics/update.py", line 17, in base_update_instance
backend_1           |     instance = self.update_instance(instance)
backend_1           |   File "/app/openslides_backend/action/actions/user/update.py", line 64, in update_instance
backend_1           |     return super().update_instance(instance)
backend_1           |   File "/app/openslides_backend/action/actions/user/user_mixin.py", line 77, in update_instance
backend_1           |     self.check_existence_of_to_and_from_users(instance)
backend_1           |   File "/app/openslides_backend/action/actions/user/user_mixin.py", line 182, in check_existence_of_to_and_from_users
backend_1           |     reduce(
backend_1           |   File "/app/openslides_backend/action/actions/user/user_mixin.py", line 183, in <lambda>
backend_1           |     (lambda x, y: x + y),  # type: ignore
backend_1           | TypeError: can only concatenate list (not "NoneType") to list

**Comment by reiterl** [comment]
No one can read the payload, because it is not formatted.

**Comment by jsangmeister** [comment]
This is the same error as in https://github.com/OpenSlides/openslides-backend/issues/1348 so I'd guess this is fixed now - maybe @r-peschke can support this?

**Comment by r-peschke** [comment]
The error described here is fixed with #1348/#1349, but the fix is (only) a  better error message: value of vote_delegations_$_from_ids must be a list, but it is type '{type(ids)} 

The client may not sent field value **null/None**, because this is the value the datastore uses for a not filled, empty field.
Problem lines in clients payload: 
       "vote_delegated_$_to_id": { "4": null}: This is the correct syntax to delete vote delegation in meeting/4
        "vote_delegations_$_from_ids": {"4": []}: This is the correct syntax to delete the vote delegations in meeting/4 for all users
        "vote_delegations_$_from_ids": {"4": [5]}: This is the correct syntax set or confirm the vote delegation from user/5, but removes all other existing relations from users in meeting/4
        "vote_delegations_$_from_ids": **{"4": null}**: This raised your error! The **null** is to risky to accept instead of [] to delete all forwarded users for meeting/4, because **null/None** is used to mark an empty field
