### ISSUE TITLE
`KeyError` in `get_related_user_models` presenter

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1428]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/app/openslides_backend/http/application.py", line 92, in __call__
    return self.wsgi_application(environ, start_response)
  File "/app/openslides_backend/http/application.py", line 82, in wsgi_application
    response = self.dispatch_request(request)
  File "/app/openslides_backend/http/application.py", line 44, in dispatch_request
    response_body, access_token = view_instance.dispatch(request)
  File "/app/openslides_backend/http/views/base_view.py", line 117, in dispatch
    return func(request)
  File "/app/openslides_backend/http/views/presenter_view.py", line 30, in presenter_route
    presenter_response, access_token = handler.handle_request(request)
  File "/app/openslides_backend/presenter/presenter.py", line 77, in handle_request
    response, access_token = self.parse_presenters(request)
  File "/app/openslides_backend/presenter/presenter.py", line 134, in parse_presenters
    result = presenter_instance.get_result()
  File "/app/openslides_backend/presenter/get_user_related_models.py", line 54, in get_result
    committees_data = self.get_committees_data(user_id)
  File "/app/openslides_backend/presenter/get_user_related_models.py", line 120, in get_committees_data
    committees[committee_nr]["cml"].append(level)
KeyError: 1
```

**Comment by reiterl** [comment]
I have looked at the code.
It seems like `user/committee_ids` doesn't fit `user/committee_$_management_level`.
The user has a committee management level for a committee, they is not in.

**Comment by reiterl** [comment]
Add a small fix to the handling.

**Comment by r-peschke** [comment]
> I have looked at the code. It seems like `user/committee_ids` doesn't fit `user/committee_$_management_level`. The user has a committee management level for a committee, they is not in.
This means the database is corrupt. To have a cml for a specific committee constitute the membership in the committee.
May be we should raise an exception?!
