### ISSUE TITLE
Wrong decimal conversion

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#1555]
Investigate the following traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/app/openslides_backend/http/application.py", line 103, in __call__
    return self.wsgi_application(environ, start_response)
  File "/app/openslides_backend/http/application.py", line 93, in wsgi_application
    response = self.dispatch_request(request)
  File "/app/openslides_backend/http/application.py", line 44, in dispatch_request
    response_body, access_token = view_instance.dispatch(request)
  File "/app/openslides_backend/http/views/base_view.py", line 117, in dispatch
    return func(request)
  File "/app/openslides_backend/http/views/action_view.py", line 46, in action_route
    response = handle_action_in_worker_thread(
  File "/app/openslides_backend/action/action_worker.py", line 57, in handle_action_in_worker_thread
    raise action_worker_thread.exception
  File "/app/openslides_backend/action/action_worker.py", line 235, in run
    self.response = self.handler.handle_request(
  File "/app/openslides_backend/action/action_handler.py", line 115, in handle_request
    results = self.execute_write_requests(self.parse_actions, payload)
  File "/app/openslides_backend/action/action_handler.py", line 156, in execute_write_requests
    write_requests, data = get_write_requests(*args)
  File "/app/openslides_backend/action/action_handler.py", line 194, in parse_actions
    write_request, results = self.perform_action(
  File "/app/openslides_backend/action/action_handler.py", line 235, in perform_action
    write_request, results = action.perform(
  File "/app/openslides_backend/action/actions/meeting/import_.py", line 93, in perform
    instance = self.base_update_instance(instance)
  File "/app/openslides_backend/action/action.py", line 325, in base_update_instance
    return self.update_instance(instance)
  File "/app/openslides_backend/action/actions/meeting/import_.py", line 213, in update_instance
    checker.run_check()
  File "/app/openslides_backend/models/checker.py", line 335, in run_check
    self.check_model(collection, model)
  File "/app/openslides_backend/models/checker.py", line 362, in check_model
    errors = self.check_normal_fields(model, collection)
  File "/app/openslides_backend/models/checker.py", line 403, in check_normal_fields
    field.validate(model[fieldname], model)
  File "/app/openslides_backend/models/fields.py", line 213, in validate
    assert Decimal(value) >= Decimal(
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by reiterl** [comment]
The problem happens e.g. if user/default_vote_weight = "ABC" in the request data.

**Comment by jsangmeister** [comment]
fixed in https://github.com/OpenSlides/openslides-backend/pull/1559
