### ISSUE TITLE
KeyError upon creating users via Participant Import

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-backend#2058]
Reproduction:
1. Perform json upload. Make sure data contains rows with data for completely new users with `is_present` == `1` -> It should work until here
2. Perform the import -> The import will fail with a KeyError

```
Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 282, in handle
     keepalive = self.handle_request(req, conn)
   File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
     respiter = self.wsgi(environ, resp.start_response)
   File "/app/openslides_backend/http/application.py", line 103, in __call__
     return self.wsgi_application(environ, start_response)
   File "/app/openslides_backend/http/application.py", line 93, in wsgi_application
     response = self.dispatch_request(request)
   File "/app/openslides_backend/http/application.py", line 44, in dispatch_request
     response_body, access_token = view_instance.dispatch(request)
   File "/app/openslides_backend/http/views/base_view.py", line 117, in dispatch
     return func(request)
   File "/app/openslides_backend/http/views/action_view.py", line 47, in action_route
     response = handle_action_in_worker_thread(
   File "/app/openslides_backend/action/action_worker.py", line 57, in handle_action_in_worker_thread
     raise action_worker_thread.exception
   File "/app/openslides_backend/action/action_worker.py", line 235, in run
     self.response = self.handler.handle_request(
   File "/app/openslides_backend/action/action_handler.py", line 115, in handle_request
     results = self.execute_write_requests(self.parse_actions, payload)
   File "/app/openslides_backend/action/action_handler.py", line 156, in execute_write_requests
     write_requests, data = get_write_requests(*args)
   File "/app/openslides_backend/action/action_handler.py", line 191, in parse_actions
     write_request, results = self.perform_action(
   File "/app/openslides_backend/action/action_handler.py", line 240, in perform_action
     write_request, results = action.perform(
   File "/app/openslides_backend/action/action.py", line 182, in perform
     instance = self.base_update_instance(instance)
   File "/app/openslides_backend/action/action.py", line 323, in base_update_instance
     return self.update_instance(instance)
   File "/app/openslides_backend/action/actions/user/base_import.py", line 40, in update_instance
     self.create_other_actions(rows)
   File "/app/openslides_backend/action/actions/user/participant_import.py", line 93, in create_other_actions
     "id": row["data"]["id"],
 KeyError: 'id'
```

**Comment by luisa-beerboom** [comment]
Seems like the import is expecting to pull the id it needs for set_present out of  the import row, but create rows don't have ids
