### ISSUE TITLE
Decimal import error

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-backend#2171]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 282, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 334, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/app/openslides_backend/http/application.py", line 103, in __call__
    return self.wsgi_application(environ, start_response)
  File "/app/openslides_backend/http/application.py", line 93, in wsgi_application
    response = self.dispatch_request(request)
  File "/app/openslides_backend/http/application.py", line 44, in dispatch_request
    response_body, access_token = view_instance.dispatch(request)
  File "/app/openslides_backend/http/views/base_view.py", line 119, in dispatch
    return func(request)
  File "/app/openslides_backend/http/views/action_view.py", line 47, in action_route
    response = handle_action_in_worker_thread(
  File "/app/openslides_backend/action/action_worker.py", line 69, in handle_action_in_worker_thread
    raise action_worker_thread.exception
  File "/app/openslides_backend/action/action_worker.py", line 242, in run
    self.response = self.handler.handle_request(
  File "/app/openslides_backend/action/action_handler.py", line 115, in handle_request
    results = self.execute_write_requests(self.parse_actions, payload)
  File "/app/openslides_backend/action/action_handler.py", line 156, in execute_write_requests
    write_requests, data = get_write_requests(*args)
  File "/app/openslides_backend/action/action_handler.py", line 191, in parse_actions
    write_request, results = self.perform_action(
  File "/app/openslides_backend/action/action_handler.py", line 240, in perform_action
    write_request, results = action.perform(
  File "/app/openslides_backend/action/action.py", line 155, in perform
    self.validate_instance(instance)
  File "/app/openslides_backend/action/mixins/import_mixins.py", line 397, in validate_instance
    entry[field] = str(Decimal("0.000000") + Decimal(entry[field]))
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
```

**Comment by luisa-beerboom** [comment]
I don't think the meeting import uses the `import_mixin`, what import is this actually?

**Comment by jsangmeister** [comment]
We should probably simply wrap it into a try-catch block like in the integer case. Most likely this suffices to fix this error.
