### ISSUE TITLE
Creating a poll for an assignment

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#500]
I just try to create an "empty" assignment poll with the following data:
```json
[
   {
      "action":"poll.create",
      "data":[
         {
            "meeting_id":1,
            "title":"Wahlgang (3)",
            "majority_method":"simple",
            "onehundred_percent_base":"valid",
            "pollmethod":"YN",
            "type":"analog",
            "options":[
               {
                  "content_object_id":"assignment/1"
               }
            ],
            "content_object_id":"assignment/1"
         }
      ]
   }
]
```

This error came up to me:
```html
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>
```

This is the stacktrace at the backend:
```
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Get response with status code 400: {'error': {'fqid': 'option/54', 'type': 3, 'type_verbose': 'MODEL_DOES_NOT_EXIST'}}
backend_1           | [2021-02-23 15:06:20 +0000] [53] [ERROR] Error handling request /system/action/handle_request
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
backend_1           |     self.handle_request(listener, req, client, addr)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
backend_1           |     respiter = self.wsgi(environ, resp.start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 128, in __call__
backend_1           |     return self.wsgi_application(environ, start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 118, in wsgi_application
backend_1           |     response = self.dispatch_request(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 48, in dispatch_request
backend_1           |     return self.default_route(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 73, in default_route
backend_1           |     response_body, access_token = view_instance.dispatch(
backend_1           |   File "/app/openslides_backend/http/views.py", line 66, in dispatch
backend_1           |     response = handler.handle_request(payload, user_id)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 96, in handle_request
backend_1           |     write_request, results = self.parse_actions(payload)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 150, in parse_actions
backend_1           |     for item in action_results:
backend_1           |   File "/app/openslides_backend/action/action.py", line 119, in perform
backend_1           |     instance = self.base_update_instance(instance)
backend_1           |   File "/app/openslides_backend/action/generics/create.py", line 24, in base_update_instance
backend_1           |     instance = self.update_instance(instance)
backend_1           |   File "/app/openslides_backend/action/actions/poll/create.py", line 127, in update_instance
backend_1           |     self.execute_other_action(
backend_1           |   File "/app/openslides_backend/action/action.py", line 398, in execute_other_action
backend_1           |     for item in action_results:
backend_1           |   File "/app/openslides_backend/action/action.py", line 122, in perform
backend_1           |     self.write_requests.extend(relation_updates)
backend_1           |   File "/app/openslides_backend/action/action.py", line 178, in handle_relation_updates
backend_1           |     relation_updates = self.relation_manager.get_relation_updates(
backend_1           |   File "/app/openslides_backend/action/relations/relation_manager.py", line 67, in get_relation_updates
backend_1           |     result = handler.perform()
backend_1           |   File "/app/openslides_backend/action/relations/single_relation_handler.py", line 154, in perform
backend_1           |     raise RuntimeError(
backend_1           | RuntimeError: You try to change a field using foreign collections that are not available.
```

Do you need more information?
Did I fail to notice anything?

**Comment by GabrielInTheWorld** [comment]
This issue has finished in favor of [openslides-backend-coordination#117](https://github.com/OpenSlides/openslides-backend-coordination/issues/117).

**Comment by FinnStutzenstein** [comment]
@GabrielInTheWorld You closed it since `assignment/1` is not valid for the content object of an option, right?

Nevertheless: The client input is not checked right. SOmeone please add a test for this and fixes the 500er.

**Comment by r-peschke** [comment]
In the options object then content_object_id is limited to object user, topic, motion. An assignment itself cannot be an option of an assignment-poll.

**Comment by FinnStutzenstein** [comment]
This is correct, but it seems, that it raises 500ers. This has to be fixed, so write a test trying to put an assignment into the `content-object_id` of an option and assert, that there is a user friendly error with a 400er status code.

**Comment by GabrielInTheWorld** [comment]
> In the options object then content_object_id is limited to object user, topic, motion. An assignment itself cannot be an option of an assignment-poll.

But there is another bug:
I sent the following payload:
```
[{'action': 'poll.create', 'data': [{'meeting_id': 1, 'title': 'Wahlgang (2)', 'majority_method': 'simple', 'onehundred_percent_base': 'valid', 'pollmethod': 'YN', 'type': 'analog', 'options': [{'content_object_id': 'user/3', 'Y': '4.000000', 'N': '4.000000'}, {'content_object_id': 'user/2', 'Y': '4.000000', 'N': '4.000000'}], 'content_object_id': 'assignment/2', 'votescast': '4.000000', 'votesinvalid': '4.000000', 'votesvalid': '4.000000'}]}]
```

and got this error:
`Fehler: The relation content_object_id requires the following fields to be equal:
option/76/meeting_id: 1
user/3/meeting_id: None`

**Comment by r-peschke** [comment]
> This is correct, but it seems, that it raises 500ers. This has to be fixed, so write a test trying to put an assignment into the `content-object_id` of an option and assert, that there is a user friendly error with a 400er status code.
This original part of this issue is fixed with a more expressive error message, i.e. in this case **"The collection 'assignment' is not available for field 'content_object_id' in collection 'option'."** and there is a test for it.
