### ISSUE TITLE
Creating a user leads into a 500 error

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#647]
I tried to create a non-temporary user with the following payload:
```json
[
  {
    "action":"user.create",
    "data":[
      {
        "username":"",
        "title":"",
        "first_name":"Chef",
        "last_name":"Koch",
        "gender":"",
        "email":"",
        "group_$_ids":{
          
        },
        "comment_$":{
          "1":""
        },
        "number_$":{
          
        },
        "structure_level_$":{
          
        },
        "about_me_$":{
          "1":""
        },
        "vote_delegations_$_from_ids":{
          
        }
      }
    ]
  }
]
```

The backend sent me back, that a user with this username already exists.
`DEBUG:openslides_backend.shared.handlers.base_handler:Error occured on index 0: A user with the username  already exists.`

As a result, I sent this payload next:
```json
[
  {
    "action":"user.create",
    "data":[
      {
        "username":"Chefkoch",
        "title":"",
        "first_name":"Chef",
        "last_name":"Koch",
        "gender":"",
        "email":"",
        "group_$_ids":{
          
        },
        "comment_$":{
          "1":""
        },
        "number_$":{
          
        },
        "structure_level_$":{
          
        },
        "about_me_$":{
          "1":""
        },
        "vote_delegations_$_from_ids":{
          
        }
      }
    ]
  }
]
```

Then, the backend throws a 500 error with the following traceback:
```
backend_1           | DEBUG:openslides_backend.shared.handlers.base_handler:Perform action user.create.
backend_1           | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): permission:9005
datastore-reader_1  | 2021-04-13T07:13:46.609: [/app/reader/flask_frontend/json_handler.py] [INFO] GET_MANY-request: {'requests': ['user/1/organisation_management_level']}
datastore-reader_1  | 172.18.0.7 - - [13/Apr/2021 07:13:46] "POST /internal/datastore/reader/get_many HTTP/1.1" 200 -
backend_1           | DEBUG:urllib3.connectionpool:http://permission:9005 "POST /internal/permission/is_allowed HTTP/1.1" 200 5
backend_1           | DEBUG:openslides_backend.services.permission.adapter:Permission service response with status code 200: True
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start RESERVE_IDS request to datastore with the following data: Collection: user, Amount: 1
backend_1           | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): datastore-writer:9011
datastore-writer_1  | 2021-04-13T07:13:46.629: [/app/writer/core/writer_service.py] [INFO] 1 ids reserved
backend_1           | DEBUG:urllib3.connectionpool:http://datastore-writer:9011 "POST /internal/datastore/writer/reserve_ids HTTP/1.1" 200 12
datastore-writer_1  | 172.18.0.10 - - [13/Apr/2021 07:13:46] "POST /internal/datastore/writer/reserve_ids HTTP/1.1" 200 -
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Get response with status code 200: {'ids': [24]}
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start EXISTS request to datastore with the following data: {"collection": "user", "filter": {"and_filter": [{"field": "username", "operator": "=", "value": "Chefkoch"}, {"field": "meta_deleted", "operator": "=", "value": false}]}}
backend_1           | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): datastore-reader:9010
datastore-reader_1  | 2021-04-13T07:13:46.647: [/app/reader/flask_frontend/json_handler.py] [INFO] EXISTS-request: {'collection': 'user', 'filter': {'and_filter': [{'field': 'username', 'operator': '=', 'value': 'Chefkoch'}, {'field': 'meta_deleted', 'operator': '=', 'value': False}]}}
datastore-reader_1  | 172.18.0.10 - - [13/Apr/2021 07:13:46] "POST /internal/datastore/reader/exists HTTP/1.1" 200 -
backend_1           | DEBUG:urllib3.connectionpool:http://datastore-reader:9010 "POST /internal/datastore/reader/exists HTTP/1.1" 200 30
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Get response with status code 200: {'exists': False, 'position': 65}
backend_1           | [2021-04-13 07:13:46 +0000] [48] [ERROR] Error handling request /system/action/handle_request
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
backend_1           |     self.handle_request(listener, req, client, addr)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
backend_1           |     respiter = self.wsgi(environ, resp.start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 121, in __call__
backend_1           |     return self.wsgi_application(environ, start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 111, in wsgi_application
backend_1           |     response = self.dispatch_request(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 41, in dispatch_request
backend_1           |     return self.default_route(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 68, in default_route
backend_1           |     response_body, access_token = view_instance.dispatch(request)
backend_1           |   File "/app/openslides_backend/http/views.py", line 62, in dispatch
backend_1           |     response = handler.handle_request(request.json, user_id, is_atomic)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 98, in handle_request
backend_1           |     results = self.execute_write_requests(self.parse_actions, payload)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 130, in execute_write_requests
backend_1           |     write_requests, data = get_write_requests(*args)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 167, in parse_actions
backend_1           |     write_request, results = self.perform_action(element, relation_manager)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 201, in perform_action
backend_1           |     write_request, results = action.perform(action_data, self.user_id)
backend_1           |   File "/app/openslides_backend/action/action.py", line 125, in perform
backend_1           |     instance = self.base_update_instance(instance)
backend_1           |   File "/app/openslides_backend/action/generics/create.py", line 24, in base_update_instance
backend_1           |     instance = self.update_instance(instance)
backend_1           |   File "/app/openslides_backend/action/actions/user/user_mixin.py", line 27, in update_instance
backend_1           |     self.check_existence_of_to_and_from_users(instance)
backend_1           |   File "/app/openslides_backend/action/actions/user/user_mixin.py", line 132, in check_existence_of_to_and_from_users
backend_1           |     reduce(
backend_1           | TypeError: reduce() of empty sequence with no initial value
```

Can anyone tell me, what goes wrong?

**Comment by jsangmeister** [comment]
@r-peschke since you wrote the code, maybe you can check this and add a test for it

**Comment by r-peschke** [comment]
> I tried to create a non-temporary user with the following payload:
>  ...
> ```json
> [
>   {
>     "action":"user.create",
>     "data":[
>       {
>         "username":"",

Why do you send an empty username? I think we should make this field required or does anybody knows a use case for it?

> The backend sent me back, that a user with this username already exists.
> `DEBUG:openslides_backend.shared.handlers.base_handler:Error occured on index 0: A user with the username already exists.`

I think this is, because first time the backend stored your user without username and on second run he detected the same, empty username. The username has to be unique.

> 
> As a result, I sent this payload next:
> 
>         "vote_delegations_$_from_ids":{
>           
>         }

This field causes the error. There may be never a 500, I will fix the error

>       }
>     ]
>   }
> ]
> ```
> 
> Then, the backend throws a 500 error with the following traceback:
> 
> Can anyone tell me, what goes wrong?
 See above

**Comment by GabrielInTheWorld** [comment]
> > I tried to create a non-temporary user with the following payload:
> > ...
> > ```json
> > [
> >   {
> >     "action":"user.create",
> >     "data":[
> >       {
> >         "username":"",
> > ```
> 
> Why do you send an empty username? I think we should make this field required or does anybody knows a use case for it?
> 

In OS3, there was only one of first_name, last_name or username required. If no username was given, a username was created from first_name + last_name.

>
> > As a result, I sent this payload next:
> > ```
> >     "vote_delegations_$_from_ids":{
> >       
> >     }
> > ```
> 
> This field causes the error. There may be never a 500, I will fix the error
> 

Ah, thanks!

**Comment by jsangmeister** [comment]
> In OS3, there was only one of first_name, last_name or username required. If no username was given, a username was created from first_name + last_name.

Yes, but AFAIK we changed this in OS4 so the username is always required. I thought this was caught by the backend - this should also be checked @r-peschke.

**Comment by r-peschke** [comment]
> > In OS3, there was only one of first_name, last_name or username required. If no username was given, a username was created from first_name + last_name.
> 
> Yes, but AFAIK we changed this in OS4 so the username is always required. I thought this was caught by the backend - this should also be checked @r-peschke.

The username in OS4 has been required in the schema options. This means, you have to mention the username, but could leave it empty. I added a required attribute in the model ([models.yml](https://github.com/OpenSlides/OpenSlides/pull/6011) and [model.py](https://github.com/OpenSlides/openslides-backend/pull/649) ) with test. The Username now needs minimum 1 char.
