### ISSUE TITLE
Backend throws Internal Server Error on agenda_item.create

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#767]
Sending the following payload:
```json
[
  {
    "action":"agenda_item.create",
    "data":[
      {
        "content_object_id":"assignment/5"
      }
    ]
  }
]
```

will give the following error:
```html
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>
```

These are the logs from backend:
```
backend_1           | DEBUG:openslides_backend.shared.handlers.base_handler:Perform action agenda_item.create.
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: {"fqid": "assignment/5", "mapped_fields": ["meeting_id", "meta_position"], "get_deleted_models": 1}
backend_1           | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): datastore-reader:9010
datastore-reader_1  | 2021-06-11T06:55:11.818: [/app/reader/flask_frontend/json_handler.py] [INFO] GET-request: {'fqid': 'assignment/5', 'mapped_fields': ['meeting_id', 'meta_position'], 'get_deleted_models': 1}
datastore-reader_1  | 172.18.0.11 - - [11/Jun/2021 06:55:11] "POST /internal/datastore/reader/get HTTP/1.1" 200 -
backend_1           | DEBUG:urllib3.connectionpool:http://datastore-reader:9010 "POST /internal/datastore/reader/get HTTP/1.1" 200 36
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Get response with status code 200: {'meeting_id': 1, 'meta_position': 471}
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: {"fqid": "user/1", "mapped_fields": ["guest_meeting_ids", "group_$1_ids", "organization_management_level"], "get_deleted_models": 1}
backend_1           | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): datastore-reader:9010
datastore-reader_1  | 2021-06-11T06:55:11.837: [/app/reader/flask_frontend/json_handler.py] [INFO] GET-request: {'fqid': 'user/1', 'mapped_fields': ['guest_meeting_ids', 'group_$1_ids', 'organization_management_level'], 'get_deleted_models': 1}
datastore-reader_1  | 172.18.0.11 - - [11/Jun/2021 06:55:11] "POST /internal/datastore/reader/get HTTP/1.1" 200 -
backend_1           | DEBUG:urllib3.connectionpool:http://datastore-reader:9010 "POST /internal/datastore/reader/get HTTP/1.1" 200 65
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Get response with status code 200: {'organization_management_level': 'superadmin', 'group_$1_ids': [2]}
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start RESERVE_IDS request to datastore with the following data: Collection: agenda_item, Amount: 1
backend_1           | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): datastore-writer:9011
datastore-writer_1  | 2021-06-11T06:55:11.855: [/app/writer/core/writer_service.py] [INFO] 1 ids reserved
datastore-writer_1  | 172.18.0.11 - - [11/Jun/2021 06:55:11] "POST /internal/datastore/writer/reserve_ids HTTP/1.1" 200 -
backend_1           | DEBUG:urllib3.connectionpool:http://datastore-writer:9011 "POST /internal/datastore/writer/reserve_ids HTTP/1.1" 200 12
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Get response with status code 200: {'ids': [42]}
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: {"fqid": "assignment/5", "mapped_fields": ["meeting_id", "meta_position"], "get_deleted_models": 1}
backend_1           | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): datastore-reader:9010
datastore-reader_1  | 2021-06-11T06:55:11.869: [/app/reader/flask_frontend/json_handler.py] [INFO] GET-request: {'fqid': 'assignment/5', 'mapped_fields': ['meeting_id', 'meta_position'], 'get_deleted_models': 1}
datastore-reader_1  | 172.18.0.11 - - [11/Jun/2021 06:55:11] "POST /internal/datastore/reader/get HTTP/1.1" 200 -
backend_1           | DEBUG:urllib3.connectionpool:http://datastore-reader:9010 "POST /internal/datastore/reader/get HTTP/1.1" 200 36
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Get response with status code 200: {'meeting_id': 1, 'meta_position': 471}
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: {"fqid": "assignment/5", "mapped_fields": ["meeting_id", "meta_position"], "get_deleted_models": 1}
backend_1           | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): datastore-reader:9010
datastore-reader_1  | 2021-06-11T06:55:11.886: [/app/reader/flask_frontend/json_handler.py] [INFO] GET-request: {'fqid': 'assignment/5', 'mapped_fields': ['meeting_id', 'meta_position'], 'get_deleted_models': 1}
datastore-reader_1  | 172.18.0.11 - - [11/Jun/2021 06:55:11] "POST /internal/datastore/reader/get HTTP/1.1" 200 -
backend_1           | DEBUG:urllib3.connectionpool:http://datastore-reader:9010 "POST /internal/datastore/reader/get HTTP/1.1" 200 36
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Get response with status code 200: {'meeting_id': 1, 'meta_position': 471}
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: {"fqid": "agenda_item/42", "mapped_fields": ["meta_position", "content_object_id"], "get_deleted_models": 1}
backend_1           | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): datastore-reader:9010
datastore-reader_1  | 2021-06-11T06:55:11.902: [/app/reader/flask_frontend/json_handler.py] [INFO] GET-request: {'fqid': 'agenda_item/42', 'mapped_fields': ['meta_position', 'content_object_id'], 'get_deleted_models': 1}
datastore-reader_1  | 2021-06-11T06:55:11.904: [/app/shared/flask_frontend/errors.py] [DEBUG] HTTP error 400: {'type': 3, 'fqid': 'agenda_item/42', 'type_verbose': 'MODEL_DOES_NOT_EXIST'}
datastore-reader_1  | 172.18.0.11 - - [11/Jun/2021 06:55:11] "POST /internal/datastore/reader/get HTTP/1.1" 400 -
backend_1           | DEBUG:urllib3.connectionpool:http://datastore-reader:9010 "POST /internal/datastore/reader/get HTTP/1.1" 400 111
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Get response with status code 400: {'error': {'fqid': 'agenda_item/42', 'type': 3, 'type_verbose': 'MODEL_DOES_NOT_EXIST'}}
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: {"fqid": "assignment/5", "mapped_fields": ["agenda_item_id", "meta_position"], "get_deleted_models": 1}
backend_1           | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): datastore-reader:9010
datastore-reader_1  | 2021-06-11T06:55:11.916: [/app/reader/flask_frontend/json_handler.py] [INFO] GET-request: {'fqid': 'assignment/5', 'mapped_fields': ['agenda_item_id', 'meta_position'], 'get_deleted_models': 1}
datastore-reader_1  | 172.18.0.11 - - [11/Jun/2021 06:55:11] "POST /internal/datastore/reader/get HTTP/1.1" 200 -
backend_1           | DEBUG:urllib3.connectionpool:http://datastore-reader:9010 "POST /internal/datastore/reader/get HTTP/1.1" 200 41
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Get response with status code 200: {'agenda_item_id': 41, 'meta_position': 471}
backend_1           | [2021-06-11 06:55:11 +0000] [49] [ERROR] Error handling request /system/action/handle_request
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
backend_1           |     self.handle_request(listener, req, client, addr)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
backend_1           |     respiter = self.wsgi(environ, resp.start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 121, in __call__
backend_1           |     return self.wsgi_application(environ, start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 111, in wsgi_application
backend_1           |     response = self.dispatch_request(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 41, in dispatch_request
backend_1           |     return self.default_route(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 68, in default_route
backend_1           |     response_body, access_token = view_instance.dispatch(request)
backend_1           |   File "/app/openslides_backend/http/views.py", line 62, in dispatch
backend_1           |     response = handler.handle_request(request.json, user_id, is_atomic)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 98, in handle_request
backend_1           |     results = self.execute_write_requests(self.parse_actions, payload)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 131, in execute_write_requests
backend_1           |     write_requests, data = get_write_requests(*args)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 168, in parse_actions
backend_1           |     write_request, results = self.perform_action(element, relation_manager)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 202, in perform_action
backend_1           |     write_request, results = action.perform(action_data, self.user_id)
backend_1           |   File "/app/openslides_backend/action/action.py", line 148, in perform
backend_1           |     self.write_requests.extend(relation_updates)
backend_1           |   File "/app/openslides_backend/action/action.py", line 267, in handle_relation_updates
backend_1           |     relation_updates = self.relation_manager.get_relation_updates(
backend_1           |   File "/app/openslides_backend/action/relations/relation_manager.py", line 70, in get_relation_updates
backend_1           |     result = handler.perform()
backend_1           |   File "/app/openslides_backend/action/relations/single_relation_handler.py", line 193, in perform
backend_1           |     handler = self.build_handler_from_chained_field(chained_field)
backend_1           |   File "/app/openslides_backend/action/relations/single_relation_handler.py", line 205, in build_handler_from_chained_field
backend_1           |     raise NotImplementedError()
backend_1           | NotImplementedError
```

**Comment by GabrielInTheWorld** [comment]
I've found the error

**Comment by jsangmeister** [comment]
Can you provide the source of the error? And, independently of that, the backend should never throw a 500 and crash. It looks like the chained fields in the relation handler provoke the error, @r-peschke can you take a look at this?

**Comment by GabrielInTheWorld** [comment]
> Can you provide the source of the error? And, independently of that, the backend should never throw a 500 and crash. It looks like the chained fields in the relation handler provoke the error, @r-peschke can you take a look at this?

Well, I have seen, that for that content-object was already an agenda-item created. So, the source must be, that I tried to create a second agenda-item with the same `content_object_id`.
Is that enough information for you? Do you need more information?
