### ISSUE TITLE
`Internal Server Error` when sending `motion.update` and `motion.set_recommendation`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#789]
I get an internal server error when I send this payload:
```json
[
  {
    "action":"motion.update",
    "data":[
      {
        "id":5
      }
    ]
  },
  {
    "action":"motion.set_recommendation",
    "data":[
      {
        "id":5,
        "recommendation_id":16
      }
    ]
  }
]
```

The stacktrace:
```
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start WRITE request to datastore with the following data: Write request: [WriteRequest(events=[{'type': <EventType.Update: 'update'>, 'fqid': FullQualifiedId('motion/5'), 'fields': {'last_modified': 1624013303}}], information={FullQualifiedId('motion/5'): ['Object updated']}, user_id=1, locked_fields={'motion/5/meeting_id': 75, 'motion/5/submitter_ids': 75, 'motion/5/state_id': 75}), WriteRequest(events=[{'type': <EventType.Update: 'update'>, 'fqid': FullQualifiedId('motion_state/16'), 'fields': {'motion_recommendation_ids': [5]}}, {'type': <EventType.Update: 'update'>, 'fqid': FullQualifiedId('motion/5'), 'fields': {'recommendation_id': 16, 'last_modified': 1624013303}}], information={FullQualifiedId('motion_state/16'): ['Object attached to motion_state'], FullQualifiedId('motion/5'): ['Object updated']}, user_id=1, locked_fields={'motion/5': 75, 'motion/5/meeting_id': 75, 'motion/5/state_id': 75, 'motion_state/15/workflow_id': 83, 'motion_state/16/recommendation_label': 74, 'motion_state/16/workflow_id': 74, 'motion_state/16/meeting_id': 74, 'motion/5/recommendation_id': 75, 'motion_state/16/motion_recommendation_ids': 74})]
backend_1           | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): datastore-writer:9011
datastore-writer_1  | 2021-06-18T10:48:22.946: [/app/writer/postgresql_backend/sql_database_backend_service.py] [INFO] Created position 84
datastore-writer_1  | 2021-06-18T10:48:22.950: [/app/shared/flask_frontend/errors.py] [DEBUG] HTTP error 400: {'type': 6, 'key': 'motion/5', 'type_verbose': 'MODEL_LOCKED'}
datastore-writer_1  | 172.18.0.10 - - [18/Jun/2021 10:48:22] "POST /internal/datastore/writer/write HTTP/1.1" 400 -
backend_1           | DEBUG:urllib3.connectionpool:http://datastore-writer:9011 "POST /internal/datastore/writer/write HTTP/1.1" 400 96
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Get response with status code 400: {'error': {'key': 'motion/5', 'type': 6, 'type_verbose': 'MODEL_LOCKED'}}
backend_1           | [2021-06-18 10:48:22 +0000] [53] [ERROR] Error handling request /system/action/handle_request
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
backend_1           |     self.handle_request(listener, req, client, addr)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
backend_1           |     respiter = self.wsgi(environ, resp.start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 121, in __call__
backend_1           |     return self.wsgi_application(environ, start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 111, in wsgi_application
backend_1           |     response = self.dispatch_request(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 41, in dispatch_request
backend_1           |     return self.default_route(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 68, in default_route
backend_1           |     response_body, access_token = view_instance.dispatch(request)
backend_1           |   File "/app/openslides_backend/http/views.py", line 62, in dispatch
backend_1           |     response = handler.handle_request(request.json, user_id, is_atomic)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 98, in handle_request
backend_1           |     results = self.execute_write_requests(self.parse_actions, payload)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 133, in execute_write_requests
backend_1           |     self.datastore.write(write_requests)
backend_1           |   File "/app/openslides_backend/services/datastore/adapter.py", line 463, in write
backend_1           |     self.retrieve(command)
backend_1           |   File "/app/openslides_backend/services/datastore/adapter.py", line 77, in retrieve
backend_1           |     + "', '".join(sorted(additional_error_message.get("keys")))
backend_1           | TypeError: 'NoneType' object is not iterable
```

I know, why this error came. But you meant, you want to know, when internal server errors occur.

**Comment by jsangmeister** [comment]
Can you rebuild the datastore-writer and try again? It could be that you use an old version there.

**Comment by GabrielInTheWorld** [comment]
> Can you rebuild the datastore-writer and try again? It could be that you use an old version there.

Ah, yes. Now, the error message
```json
{
  "success":false,
  "message":"Datastore service sends HTTP 400. The following locks were broken: 'motion/7'"
}
```
occurs. I don't know, if this is intended...
