### ISSUE TITLE
Cannot start backend

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-backend#822]
```
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
backend_1           |     return _run_code(code, main_globals, None,
backend_1           |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
backend_1           |     exec(code, run_globals)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/debugpy/__main__.py", line 45, in <module>
backend_1           |     cli.main()
backend_1           |   File "/usr/local/lib/python3.8/site-packages/debugpy/server/cli.py", line 444, in main
backend_1           |     run()
backend_1           |   File "/usr/local/lib/python3.8/site-packages/debugpy/server/cli.py", line 285, in run_file
backend_1           |     runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
backend_1           |   File "/usr/local/lib/python3.8/runpy.py", line 282, in run_path
backend_1           |     return _run_code(code, mod_globals, init_globals,
backend_1           |   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
backend_1           |     exec(code, run_globals)
backend_1           |   File "openslides_backend/__main__.py", line 1, in <module>
backend_1           |     from openslides_backend.main import main
backend_1           |   File "/app/openslides_backend/main.py", line 13, in <module>
backend_1           |     from .shared.interfaces.wsgi import WSGIApplication
backend_1           |   File "/app/openslides_backend/shared/interfaces/wsgi.py", line 9, in <module>
backend_1           |     from .services import Services
backend_1           |   File "/app/openslides_backend/shared/interfaces/services.py", line 4, in <module>
backend_1           |     from ...services.datastore.interface import DatastoreService
backend_1           |   File "/app/openslides_backend/services/datastore/interface.py", line 4, in <module>
backend_1           |     from readerlib import DeletedModelsBehaviour
backend_1           |   File "/usr/local/lib/python3.8/site-packages/readerlib/__init__.py", line 1, in <module>
backend_1           |     from reader.app import register_services
backend_1           |   File "/usr/local/lib/python3.8/site-packages/reader/app.py", line 1, in <module>
backend_1           |     from reader.core import setup_di as core_setup_di
backend_1           |   File "/usr/local/lib/python3.8/site-packages/reader/core/__init__.py", line 1, in <module>
backend_1           |     from .reader import Reader
backend_1           |   File "/usr/local/lib/python3.8/site-packages/reader/core/reader.py", line 3, in <module>
backend_1           |     from shared.typing import Model
backend_1           | ImportError: cannot import name 'Model' from 'shared.typing' (openslides_backend/shared/typing.py)
docker_backend_1 exited with code 1
```

@jsangmeister Seems like a name clash -> The reader tries to import `shared`, but `openslides_backend/shared` is found. This would support wrapping everything in `datastore.`.

**Comment by FinnStutzenstein** [comment]
We'll modify the DS.

**Comment by FinnStutzenstein** [comment]
Work in Progress: https://github.com/OpenSlides/openslides-datastore-service/pull/134 and https://github.com/OpenSlides/openslides-backend/pull/823

@jsangmeister Lets have a look at it tomorrow.
