### ISSUE TITLE
Internal Server Error on `motion.follow_recommendation`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#824]
I sent this payload:
```json
[
  {
    "action":"motion.follow_recommendation",
    "data":[
      {
        "id":12
      }
    ]
  }
]
```

Then this error occurs:
```
backend_1           | [2021-07-07 12:47:53 +0000] [60] [ERROR] Error handling request /system/action/handle_request
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
backend_1           |     self.handle_request(listener, req, client, addr)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
backend_1           |     respiter = self.wsgi(environ, resp.start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 121, in __call__
backend_1           |     return self.wsgi_application(environ, start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 111, in wsgi_application
backend_1           |     response = self.dispatch_request(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 41, in dispatch_request
backend_1           |     return self.default_route(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 68, in default_route
backend_1           |     response_body, access_token = view_instance.dispatch(request)
backend_1           |   File "/app/openslides_backend/http/views.py", line 62, in dispatch
backend_1           |     response = handler.handle_request(request.json, user_id, is_atomic)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 98, in handle_request
backend_1           |     results = self.execute_write_requests(self.parse_actions, payload)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 131, in execute_write_requests
backend_1           |     write_requests, data = get_write_requests(*args)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 168, in parse_actions
backend_1           |     write_request, results = self.perform_action(element, relation_manager)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 202, in perform_action
backend_1           |     write_request, results = action.perform(action_data, self.user_id)
backend_1           |   File "/app/openslides_backend/action/action.py", line 145, in perform
backend_1           |     instance = self.base_update_instance(instance)
backend_1           |   File "/app/openslides_backend/action/generics/update.py", line 17, in base_update_instance
backend_1           |     instance = self.update_instance(instance)
backend_1           |   File "/app/openslides_backend/action/actions/motion/follow_recommendation.py", line 47, in update_instance
backend_1           |     recommendation_extension = instance.pop("recommendation_extension")
backend_1           | KeyError: 'recommendation_extension'
```

**Comment by jsangmeister** [comment]
Similar issue to #796: the `pop()` just needs to get a default value of `None` and this should work. A test verifying this should be added.

**Comment by jsangmeister** [comment]
(marking high cause it's quickly done)
