### ISSUE TITLE
`len(user[group_field]):` -> leads to `TypeError: object of Type 'NoneType' has no len()`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#885]
I sent this payload: 
```json
[
  {
    "action":"meeting.update",
    "data":[
      {
        "name":"Der Erste",
        "description":"",
        "location":"",
        "start_time":1627855200,
        "end_time":1627855200,
        "organization_tag_ids":[
          
        ],
        "jitsi_domain":"",
        "jitsi_room_name":"",
        "jitsi_room_password":"",
        "id":2
      }
    ]
  },
  {
    "action":"user.update",
    "data":[
      {
        "id":2,
        "group_$_ids":{
          "2":[
            
          ]
        }
      },
      {
        "id":3,
        "group_$_ids":{
          "2":[
            
          ]
        }
      },
      {
        "id":4,
        "group_$_ids":{
          "2":[
            7,
            6
          ]
        }
      }
    ]
  }
]
```

and got this error (with status code `500`):
```
backend_1           | [2021-08-02 14:47:58 +0000] [52] [ERROR] Error handling request /system/action/handle_request
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
backend_1           |     self.handle_request(listener, req, client, addr)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
backend_1           |     respiter = self.wsgi(environ, resp.start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 121, in __call__
backend_1           |     return self.wsgi_application(environ, start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 111, in wsgi_application
backend_1           |     response = self.dispatch_request(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 41, in dispatch_request
backend_1           |     return self.default_route(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 68, in default_route
backend_1           |     response_body, access_token = view_instance.dispatch(request)
backend_1           |   File "/app/openslides_backend/http/views.py", line 62, in dispatch
backend_1           |     response = handler.handle_request(request.json, user_id, is_atomic)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 98, in handle_request
backend_1           |     results = self.execute_write_requests(self.parse_actions, payload)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 131, in execute_write_requests
backend_1           |     write_requests, data = get_write_requests(*args)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 168, in parse_actions
backend_1           |     write_request, results = self.perform_action(element, relation_manager)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 203, in perform_action
backend_1           |     write_request, results = action.perform(action_data, self.user_id)
backend_1           |   File "/app/openslides_backend/action/action.py", line 148, in perform
backend_1           |     self.write_requests.extend(relation_updates)
backend_1           |   File "/app/openslides_backend/action/action.py", line 267, in handle_relation_updates
backend_1           |     relation_updates = self.relation_manager.get_relation_updates(
backend_1           |   File "/app/openslides_backend/action/relations/relation_manager.py", line 100, in get_relation_updates
backend_1           |     self.call_calculated_field_handlers(relations, **call)
backend_1           |   File "/app/openslides_backend/action/relations/relation_manager.py", line 218, in call_calculated_field_handlers
backend_1           |     result = handler_instance.process_field(field, field_name, instance, action)
backend_1           |   File "/app/openslides_backend/action/relations/meeting_user_ids_handler.py", line 47, in process_field
backend_1           |     if len(user[group_field]):
backend_1           | TypeError: object of type 'NoneType' has no len()
```

**Comment by GabrielInTheWorld** [comment]
I tagged it `high`, because I often get this error when I am editting a meeting
