### ISSUE TITLE
`AssertionError` after starting the first time

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#893]
I cleaned up my OpenSlides-repo using `make stop-dev`, updated the sub-modules and executed then `make run-dev`.
The backend exited with code 1. Here is the traceback:

``` 
backend_1           | Running migrations.
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/datastore/migrations/migration_handler.py", line 98, in run_checks
backend_1           |     self.assert_not_too_high_migration_index()
backend_1           |   File "/usr/local/lib/python3.8/site-packages/datastore/migrations/migration_handler.py", line 116, in assert_not_too_high_migration_index
backend_1           |     self.connection.query_single_value(
backend_1           |   File "/usr/local/lib/python3.8/site-packages/datastore/shared/postgresql_backend/pg_connection_handler.py", line 178, in query_single_value
backend_1           |     cursor.execute(prepared_query, arguments)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/psycopg2/extras.py", line 146, in execute
backend_1           |     return super(DictCursor, self).execute(query, vars)
backend_1           | psycopg2.errors.UndefinedColumn: column "migration_index" does not exist
backend_1           | LINE 1: select max(migration_index) from positions
backend_1           |                    ^
backend_1           | 
backend_1           | 
backend_1           | During handling of the above exception, another exception occurred:
backend_1           | 
backend_1           | Traceback (most recent call last):
backend_1           |   File "migrations/migrate.py", line 119, in <module>
backend_1           |     sys.exit(main())
backend_1           |   File "migrations/migrate.py", line 97, in main
backend_1           |     handler.migrate()
backend_1           |   File "/usr/local/lib/python3.8/site-packages/datastore/migrations/migration_handler.py", line 84, in migrate
backend_1           |     if self.run_checks():
backend_1           |   File "/usr/local/lib/python3.8/site-packages/datastore/migrations/migration_handler.py", line 101, in run_checks
backend_1           |     return True
backend_1           |   File "/usr/local/lib/python3.8/site-packages/datastore/shared/postgresql_backend/pg_connection_handler.py", line 72, in __exit__
backend_1           |     assert self.connection.closed > 0
backend_1           | AssertionError
```

**Comment by GabrielInTheWorld** [comment]
Nevermind, it seems, that the datastore had to be started again and build the database.
