### ISSUE TITLE
`meeting.import` throws an `Internal Server Error`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#927]
```
backend_1           | DEBUG:openslides_backend.shared.handlers.base_handler:Perform action meeting.import.
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='user/1', mapped_fields={'meta_position', 'organization_management_level', 'committee_$2_management_level'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | [2021-09-07 12:29:19 +0000] [56] [ERROR] Error handling request /system/action/handle_request
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
backend_1           |     self.handle_request(listener, req, client, addr)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
backend_1           |     respiter = self.wsgi(environ, resp.start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 121, in __call__
backend_1           |     return self.wsgi_application(environ, start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 111, in wsgi_application
backend_1           |     response = self.dispatch_request(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 41, in dispatch_request
backend_1           |     return self.default_route(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 68, in default_route
backend_1           |     response_body, access_token = view_instance.dispatch(request)
backend_1           |   File "/app/openslides_backend/http/views.py", line 61, in dispatch
backend_1           |     response = handler.handle_request(request.json, user_id, is_atomic)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 98, in handle_request
backend_1           |     results = self.execute_write_requests(self.parse_actions, payload)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 131, in execute_write_requests
backend_1           |     write_requests, data = get_write_requests(*args)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 168, in parse_actions
backend_1           |     write_request, results = self.perform_action(element, relation_manager)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 203, in perform_action
backend_1           |     write_request, results = action.perform(action_data, self.user_id)
backend_1           |   File "/app/openslides_backend/action/actions/meeting/import_.py", line 62, in perform
backend_1           |     instance = self.base_update_instance(instance)
backend_1           |   File "/app/openslides_backend/action/action.py", line 251, in base_update_instance
backend_1           |     return self.update_instance(instance)
backend_1           |   File "/app/openslides_backend/action/actions/meeting/import_.py", line 75, in update_instance
backend_1           |     self.check_usernames_and_generate_new_ones(meeting_json)
backend_1           |   File "/app/openslides_backend/action/actions/meeting/import_.py", line 112, in check_usernames_and_generate_new_ones
backend_1           |     template_username = entry["username"]
backend_1           | TypeError: string indices must be integers
```

I sent this file
```json
[
  {
    "action":"meeting.import",
    "data":[
      {
        "committee_id":2,
        "meeting":{
          "_migration_index":3,
          "organization":{
            "1":{
              "id":1,
              "name":"[Your organization]",
              "description":"",
              "legal_notice":"<a href=\"http://www.openslides.org\">OpenSlides</a> is a free web based presentation and assembly system for visualizing and controlling agenda, motions and elections of an assembly. The event organizer is resposible for the content.",
              "privacy_policy":"",
              "login_text":"Welcome to OpenSlides. Please login.",
              "theme":"openslides-default-light-theme",
              "reset_password_verbose_errors":false,
              "enable_electronic_voting":false,
              "limit_of_meetings":0,
              "committee_ids":[
                1
              ],
              "active_meeting_ids":[
                1
              ],
              "resource_ids":[
                
              ],
              "organization_tag_ids":[
                
              ]
            }
          },
          "user":{
            "1":{
              "id":1,
              "username":"superadmin",
              "title":"",
              "first_name":"",
              "last_name":"Administrator",
              "is_active":true,
              "is_physical_person":true,
              "password":"",
              "default_password":"",
              "can_change_own_password":true,
              "gender":null,
              "email":"",
              "default_number":"",
              "default_structure_level":"",
              "default_vote_weight":"1.000000",
              "last_email_send":null,
              "is_demo_user":false,
              "organization_management_level":"superadmin",
              "is_present_in_meeting_ids":[
                
              ],
              "committee_ids":[
                
              ],
              "committee_$_management_level":[
                
              ],
              "comment_$":[
                
              ],
              "number_$":[
                
              ],
              "structure_level_$":[
                
              ],
              "about_me_$":[
                
              ],
              "vote_weight_$":[
                
              ],
              "group_$_ids":[
                
              ],
              "speaker_$_ids":[
                
              ],
              "personal_note_$_ids":[
                
              ],
              "supported_motion_$_ids":[
                
              ],
              "submitted_motion_$_ids":[
                
              ],
              "poll_voted_$_ids":[
                
              ],
              "option_$_ids":[
                
              ],
              "vote_$_ids":[
                
              ],
              "vote_delegated_vote_$_ids":[
                
              ],
              "assignment_candidate_$_ids":[
                
              ],
              "projection_$_ids":[
                
              ],
              "vote_delegated_$_to_id":[
                
              ],
              "vote_delegations_$_from_ids":[
                
              ],
              "meeting_ids":[
                
              ]
            }
          },
          "resource":{
            
          },
          "organization_tag":{
            
          },
          "committee":{
            "1":{
              "id":1,
              "name":"Default committee",
              "description":"",
              "meeting_ids":[
                1
              ],
              "template_meeting_id":null,
              "default_meeting_id":1,
              "user_ids":[
                
              ],
              "forward_to_committee_ids":[
                
              ],
              "receive_forwardings_from_committee_ids":[
                
              ],
              "organization_tag_ids":[
                
              ],
              "organization_id":1
            }
          },
          "meeting":{
            "1":{
              "id":1,
              "welcome_title":"Welcome to OpenSlides",
              "welcome_text":"[Space for your welcome text]",
              "name":"Default meeting",
              "is_active_in_organization_id":1,
              "description":"",
              "location":"",
              "start_time":0,
              "end_time":0,
              "imported_at":null,
              "jitsi_domain":"",
              "jitsi_room_name":"",
              "jitsi_room_password":"",
              "enable_chat":false,
              "url_name":"",
              "template_for_committee_id":null,
              "enable_anonymous":false,
              "custom_translations":{
                
              },
              "conference_show":false,
              "conference_auto_connect":false,
              "conference_los_restriction":false,
              "conference_stream_url":"",
              "conference_stream_poster_url":"",
              "conference_open_microphone":true,
              "conference_open_video":true,
              "conference_auto_connect_next_speakers":0,
              "conference_enable_helpdesk":false,
              "applause_enable":false,
              "applause_type":"applause-type-bar",
              "applause_show_level":false,
              "applause_min_amount":1,
              "applause_max_amount":0,
              "applause_timeout":5,
              "applause_particle_image_url":"",
              "projector_countdown_default_time":60,
              "projector_countdown_warning_time":0,
              "export_csv_encoding":"utf-8",
              "export_csv_separator":",",
              "export_pdf_pagenumber_alignment":"center",
              "export_pdf_fontsize":10,
              "export_pdf_pagesize":"A4",
              "agenda_show_subtitles":false,
              "agenda_enable_numbering":true,
              "agenda_number_prefix":"",
              "agenda_numeral_system":"arabic",
              "agenda_item_creation":"default_yes",
              "agenda_new_items_default_visibility":"internal",
              "agenda_show_internal_items_on_projector":false,
              "list_of_speakers_amount_last_on_projector":1,
              "list_of_speakers_amount_next_on_projector":-1,
              "list_of_speakers_couple_countdown":true,
              "list_of_speakers_show_amount_of_speakers_on_slide":true,
              "list_of_speakers_present_users_only":false,
              "list_of_speakers_show_first_contribution":false,
              "list_of_speakers_enable_point_of_order_speakers":false,
              "list_of_speakers_enable_pro_contra_speech":false,
              "list_of_speakers_can_set_contribution_self":false,
              "list_of_speakers_speaker_note_for_everyone":false,
              "list_of_speakers_initially_closed":false,
              "motions_default_workflow_id":1,
              "motions_default_amendment_workflow_id":1,
              "motions_default_statute_amendment_workflow_id":1,
              "motions_preamble":"The assembly may decide:",
              "motions_default_line_numbering":"none",
              "motions_line_length":90,
              "motions_reason_required":false,
              "motions_enable_text_on_projector":true,
              "motions_enable_reason_on_projector":true,
              "motions_enable_sidebox_on_projector":false,
              "motions_enable_recommendation_on_projector":true,
              "motions_show_referring_motions":true,
              "motions_show_sequential_number":true,
              "motions_recommendations_by":"",
              "motions_statute_recommendations_by":"",
              "motions_recommendation_text_mode":"original",
              "motions_default_sorting":"number",
              "motions_number_type":"per_category",
              "motions_number_min_digits":1,
              "motions_number_with_blank":false,
              "motions_statutes_enabled":true,
              "motions_amendments_enabled":true,
              "motions_amendments_in_main_list":true,
              "motions_amendments_of_amendments":false,
              "motions_amendments_prefix":"-",
              "motions_amendments_text_mode":"freestyle",
              "motions_amendments_multiple_paragraphs":true,
              "motions_supporters_min_amount":1,
              "motions_export_title":"Motions",
              "motions_export_preamble":"",
              "motions_export_submitter_recommendation":false,
              "motions_export_follow_recommendation":false,
              "motion_poll_ballot_paper_selection":"CUSTOM_NUMBER",
              "motion_poll_ballot_paper_number":8,
              "motion_poll_default_type":"analog",
              "motion_poll_default_100_percent_base":"YNA",
              "motion_poll_default_group_ids":[
                3
              ],
              "users_sort_by":"first_name",
              "users_enable_presence_view":true,
              "users_enable_vote_weight":true,
              "users_allow_self_set_present":true,
              "users_pdf_welcometitle":"Welcome to OpenSlides",
              "users_pdf_welcometext":"[Place for your welcome and help text]",
              "users_pdf_url":"https://example.com",
              "users_pdf_wlan_ssid":"",
              "users_pdf_wlan_password":"",
              "users_pdf_wlan_encryption":"",
              "users_email_sender":"noreply@yourdomain.com",
              "users_email_replyto":"",
              "users_email_subject":"Your login for {event_name}",
              "users_email_body":"Dear {name},\n\nthis is your OpenSlides login for the event {event_name}:\n\n    {url}\n    username: {username}\n    password: {password}\n\nThis email was generated automatically.",
              "assignment_poll_ballot_paper_selection":"CUSTOM_NUMBER",
              "assignment_poll_ballot_paper_number":8,
              "assignments_export_title":"Elections",
              "assignments_export_preamble":"",
              "assignment_poll_add_candidates_to_list_of_speakers":true,
              "assignment_poll_sort_poll_result_by_votes":true,
              "assignment_poll_default_type":"nominal",
              "assignment_poll_default_method":"votes",
              "assignment_poll_default_100_percent_base":"valid",
              "assignment_poll_default_group_ids":[
                3
              ],
              "poll_ballot_paper_selection":"CUSTOM_NUMBER",
              "poll_ballot_paper_number":8,
              "poll_sort_poll_result_by_votes":true,
              "poll_default_type":"nominal",
              "poll_default_method":"votes",
              "poll_default_100_percent_base":"valid",
              "poll_default_group_ids":[
                3
              ],
              "poll_couple_countdown":true,
              "projector_ids":[
                1
              ],
              "all_projection_ids":[
                
              ],
              "projector_message_ids":[
                
              ],
              "projector_countdown_ids":[
                1,
                2
              ],
              "tag_ids":[
                
              ],
              "agenda_item_ids":[
                
              ],
              "list_of_speakers_ids":[
                
              ],
              "speaker_ids":[
                
              ],
              "topic_ids":[
                
              ],
              "group_ids":[
                1,
                2,
                3,
                4
              ],
              "mediafile_ids":[
                
              ],
              "motion_ids":[
                
              ],
              "motion_comment_section_ids":[
                
              ],
              "motion_category_ids":[
                
              ],
              "motion_block_ids":[
                
              ],
              "motion_workflow_ids":[
                1
              ],
              "motion_statute_paragraph_ids":[
                
              ],
              "motion_comment_ids":[
                
              ],
              "motion_submitter_ids":[
                
              ],
              "motion_change_recommendation_ids":[
                
              ],
              "motion_state_ids":[
                1,
                2,
                3,
                4
              ],
              "poll_ids":[
                
              ],
              "option_ids":[
                
              ],
              "vote_ids":[
                
              ],
              "assignment_ids":[
                
              ],
              "assignment_candidate_ids":[
                
              ],
              "personal_note_ids":[
                
              ],
              "chat_group_ids":[
                
              ],
              "logo_$_id":[
                
              ],
              "font_$_id":[
                
              ],
              "committee_id":1,
              "default_meeting_for_committee_id":1,
              "organization_tag_ids":[
                
              ],
              "present_user_ids":[
                
              ],
              "user_ids":[
                
              ],
              "reference_projector_id":1,
              "list_of_speakers_countdown_id":1,
              "poll_countdown_id":2,
              "default_projector_$_id":[
                "agenda_all_items",
                "topics",
                "list_of_speakers",
                "current_list_of_speakers",
                "motion",
                "amendment",
                "motion_block",
                "assignment",
                "user",
                "mediafile",
                "projector_message",
                "projector_countdowns",
                "assignment_poll",
                "motion_poll",
                "poll"
              ],
              "default_projector_$agenda_all_items_id":1,
              "default_projector_$topics_id":1,
              "default_projector_$list_of_speakers_id":1,
              "default_projector_$current_list_of_speakers_id":1,
              "default_projector_$motion_id":1,
              "default_projector_$amendment_id":1,
              "default_projector_$motion_block_id":1,
              "default_projector_$assignment_id":1,
              "default_projector_$user_id":1,
              "default_projector_$mediafile_id":1,
              "default_projector_$projector_message_id":1,
              "default_projector_$projector_countdowns_id":1,
              "default_projector_$assignment_poll_id":1,
              "default_projector_$motion_poll_id":1,
              "default_projector_$poll_id":1,
              "projection_ids":[
                
              ],
              "default_group_id":1,
              "admin_group_id":2
            }
          },
          "group":{
            "1":{
              "id":1,
              "name":"Default",
              "permissions":[
                "agenda_item.can_see",
                "agenda_item.can_see_internal",
                "assignment.can_see",
                "list_of_speakers.can_see",
                "mediafile.can_see",
                "meeting.can_see_frontpage",
                "meeting.can_see_autopilot",
                "motion.can_see",
                "projector.can_see",
                "user.can_see"
              ],
              "user_ids":[
                
              ],
              "default_group_for_meeting_id":1,
              "admin_group_for_meeting_id":null,
              "mediafile_access_group_ids":[
                
              ],
              "mediafile_inherited_access_group_ids":[
                
              ],
              "read_comment_section_ids":[
                
              ],
              "write_comment_section_ids":[
                
              ],
              "read_chat_group_ids":[
                
              ],
              "write_chat_group_ids":[
                
              ],
              "poll_ids":[
                
              ],
              "used_as_motion_poll_default_id":null,
              "used_as_assignment_poll_default_id":null,
              "used_as_poll_default_id":null,
              "meeting_id":1
            },
            "2":{
              "id":2,
              "name":"Admin",
              "permissions":[
                
              ],
              "user_ids":[
                
              ],
              "default_group_for_meeting_id":null,
              "admin_group_for_meeting_id":1,
              "mediafile_access_group_ids":[
                
              ],
              "mediafile_inherited_access_group_ids":[
                
              ],
              "read_comment_section_ids":[
                
              ],
              "write_comment_section_ids":[
                
              ],
              "read_chat_group_ids":[
                
              ],
              "write_chat_group_ids":[
                
              ],
              "poll_ids":[
                
              ],
              "used_as_motion_poll_default_id":null,
              "used_as_assignment_poll_default_id":null,
              "used_as_poll_default_id":null,
              "meeting_id":1
            },
            "3":{
              "id":3,
              "name":"Delegates",
              "permissions":[
                "agenda_item.can_see",
                "agenda_item.can_see_internal",
                "assignment.can_see",
                "assignment.can_nominate_other",
                "assignment.can_nominate_self",
                "list_of_speakers.can_see",
                "list_of_speakers.can_be_speaker",
                "mediafile.can_see",
                "meeting.can_see_frontpage",
                "meeting.can_see_autopilot",
                "motion.can_see",
                "motion.can_create",
                "motion.can_create_amendments",
                "motion.can_support",
                "projector.can_see",
                "user.can_see"
              ],
              "user_ids":[
                
              ],
              "default_group_for_meeting_id":null,
              "admin_group_for_meeting_id":null,
              "mediafile_access_group_ids":[
                
              ],
              "mediafile_inherited_access_group_ids":[
                
              ],
              "read_comment_section_ids":[
                
              ],
              "write_comment_section_ids":[
                
              ],
              "read_chat_group_ids":[
                
              ],
              "write_chat_group_ids":[
                
              ],
              "poll_ids":[
                
              ],
              "used_as_motion_poll_default_id":1,
              "used_as_assignment_poll_default_id":1,
              "used_as_poll_default_id":1,
              "meeting_id":1
            },
            "4":{
              "id":4,
              "name":"Staff",
              "permissions":[
                "agenda_item.can_see",
                "agenda_item.can_see_internal",
                "agenda_item.can_manage",
                "assignment.can_see",
                "assignment.can_nominate_other",
                "assignment.can_manage",
                "assignment.can_nominate_self",
                "list_of_speakers.can_see",
                "list_of_speakers.can_be_speaker",
                "list_of_speakers.can_manage",
                "mediafile.can_see",
                "mediafile.can_manage",
                "meeting.can_see_frontpage",
                "meeting.can_see_autopilot",
                "motion.can_see",
                "motion.can_manage",
                "motion.can_manage_metadata",
                "motion.can_manage_polls",
                "motion.can_see_internal",
                "motion.can_create",
                "motion.can_create_amendments",
                "poll.can_manage",
                "projector.can_see",
                "projector.can_manage",
                "tag.can_manage",
                "user.can_see",
                "user.can_see_extra_data",
                "user.can_manage"
              ],
              "user_ids":[
                
              ],
              "default_group_for_meeting_id":null,
              "admin_group_for_meeting_id":null,
              "mediafile_access_group_ids":[
                
              ],
              "mediafile_inherited_access_group_ids":[
                
              ],
              "read_comment_section_ids":[
                
              ],
              "write_comment_section_ids":[
                
              ],
              "read_chat_group_ids":[
                
              ],
              "write_chat_group_ids":[
                
              ],
              "poll_ids":[
                
              ],
              "used_as_motion_poll_default_id":null,
              "used_as_assignment_poll_default_id":null,
              "used_as_poll_default_id":null,
              "meeting_id":1
            }
          },
          "personal_note":{
            
          },
          "tag":{
            
          },
          "agenda_item":{
            
          },
          "list_of_speakers":{
            
          },
          "speaker":{
            
          },
          "topic":{
            
          },
          "motion":{
            
          },
          "motion_submitter":{
            
          },
          "motion_comment":{
            
          },
          "motion_comment_section":{
            
          },
          "motion_category":{
            
          },
          "motion_block":{
            
          },
          "motion_change_recommendation":{
            
          },
          "motion_state":{
            "1":{
              "id":1,
              "name":"submitted",
              "recommendation_label":null,
              "css_class":"lightblue",
              "restrictions":[
                
              ],
              "allow_support":true,
              "allow_create_poll":true,
              "allow_submitter_edit":true,
              "set_number":true,
              "show_state_extension_field":false,
              "merge_amendment_into_final":"undefined",
              "show_recommendation_extension_field":false,
              "next_state_ids":[
                2,
                3,
                4
              ],
              "previous_state_ids":[
                
              ],
              "motion_ids":[
                
              ],
              "motion_recommendation_ids":[
                
              ],
              "workflow_id":1,
              "first_state_of_workflow_id":1,
              "meeting_id":1
            },
            "2":{
              "id":2,
              "name":"accepted",
              "recommendation_label":"Acceptance",
              "css_class":"green",
              "restrictions":[
                
              ],
              "allow_support":false,
              "allow_create_poll":false,
              "allow_submitter_edit":false,
              "set_number":true,
              "show_state_extension_field":false,
              "merge_amendment_into_final":"undefined",
              "show_recommendation_extension_field":false,
              "next_state_ids":[
                
              ],
              "previous_state_ids":[
                1
              ],
              "motion_ids":[
                
              ],
              "motion_recommendation_ids":[
                
              ],
              "workflow_id":1,
              "first_state_of_workflow_id":null,
              "meeting_id":1
            },
            "3":{
              "id":3,
              "name":"rejected",
              "recommendation_label":"Rejection",
              "css_class":"red",
              "restrictions":[
                
              ],
              "allow_support":false,
              "allow_create_poll":false,
              "allow_submitter_edit":false,
              "set_number":true,
              "show_state_extension_field":false,
              "merge_amendment_into_final":"undefined",
              "show_recommendation_extension_field":false,
              "next_state_ids":[
                
              ],
              "previous_state_ids":[
                1
              ],
              "motion_ids":[
                
              ],
              "motion_recommendation_ids":[
                
              ],
              "workflow_id":1,
              "first_state_of_workflow_id":null,
              "meeting_id":1
            },
            "4":{
              "id":4,
              "name":"not decided",
              "recommendation_label":"No decision",
              "css_class":"grey",
              "restrictions":[
                
              ],
              "allow_support":false,
              "allow_create_poll":false,
              "allow_submitter_edit":false,
              "set_number":true,
              "show_state_extension_field":false,
              "merge_amendment_into_final":"undefined",
              "show_recommendation_extension_field":false,
              "next_state_ids":[
                
              ],
              "previous_state_ids":[
                1
              ],
              "motion_ids":[
                
              ],
              "motion_recommendation_ids":[
                
              ],
              "workflow_id":1,
              "first_state_of_workflow_id":null,
              "meeting_id":1
            }
          },
          "motion_workflow":{
            "1":{
              "id":1,
              "name":"Simple Workflow",
              "state_ids":[
                1,
                2,
                3,
                4
              ],
              "first_state_id":1,
              "default_workflow_meeting_id":1,
              "default_amendment_workflow_meeting_id":1,
              "default_statute_amendment_workflow_meeting_id":1,
              "meeting_id":1
            }
          },
          "motion_statute_paragraph":{
            
          },
          "poll":{
            
          },
          "option":{
            
          },
          "vote":{
            
          },
          "assignment":{
            
          },
          "assignment_candidate":{
            
          },
          "mediafile":{
            
          },
          "projector":{
            "1":{
              "id":1,
              "name":"Default projector",
              "scale":0,
              "scroll":0,
              "width":1220,
              "aspect_ratio_numerator":4,
              "aspect_ratio_denominator":3,
              "color":"#000000",
              "background_color":"#ffffff",
              "header_background_color":"#317796",
              "header_font_color":"#f5f5f5",
              "header_h1_color":"#317796",
              "chyron_background_color":"#317796",
              "chyron_font_color":"#ffffff",
              "show_header_footer":true,
              "show_title":true,
              "show_logo":true,
              "show_clock":true,
              "current_projection_ids":[
                
              ],
              "preview_projection_ids":[
                
              ],
              "history_projection_ids":[
                
              ],
              "used_as_reference_projector_meeting_id":1,
              "used_as_default_$_in_meeting_id":[
                "agenda_all_items",
                "topics",
                "list_of_speakers",
                "current_list_of_speakers",
                "motion",
                "amendment",
                "motion_block",
                "assignment",
                "user",
                "mediafile",
                "projector_message",
                "projector_countdowns",
                "assignment_poll",
                "motion_poll",
                "poll"
              ],
              "used_as_default_$agenda_all_items_in_meeting_id":1,
              "used_as_default_$topics_in_meeting_id":1,
              "used_as_default_$list_of_speakers_in_meeting_id":1,
              "used_as_default_$current_list_of_speakers_in_meeting_id":1,
              "used_as_default_$motion_in_meeting_id":1,
              "used_as_default_$amendment_in_meeting_id":1,
              "used_as_default_$motion_block_in_meeting_id":1,
              "used_as_default_$assignment_in_meeting_id":1,
              "used_as_default_$user_in_meeting_id":1,
              "used_as_default_$mediafile_in_meeting_id":1,
              "used_as_default_$projector_message_in_meeting_id":1,
              "used_as_default_$projector_countdowns_in_meeting_id":1,
              "used_as_default_$assignment_poll_in_meeting_id":1,
              "used_as_default_$motion_poll_in_meeting_id":1,
              "used_as_default_$poll_in_meeting_id":1,
              "meeting_id":1
            }
          },
          "projection":{
            
          },
          "projector_message":{
            
          },
          "projector_countdown":{
            "1":{
              "id":1,
              "title":"List of speaker countdown",
              "description":"",
              "default_time":60,
              "countdown_time":60,
              "running":false,
              "projection_ids":[
                
              ],
              "used_as_list_of_speaker_countdown_meeting_id":1,
              "used_as_poll_countdown_meeting_id":null,
              "meeting_id":1
            },
            "2":{
              "id":2,
              "title":"Voting countdown",
              "description":"",
              "default_time":60,
              "countdown_time":60,
              "running":false,
              "projection_ids":[
                
              ],
              "used_as_list_of_speaker_countdown_meeting_id":null,
              "used_as_poll_countdown_meeting_id":1,
              "meeting_id":1
            }
          },
          "chat_group":{
            
          }
        }
      }
    ]
  }
]
```

Please catch the Internal Server Error here

**Comment by emanuelschuetze** [comment]
not important for 4.x

**Comment by jsangmeister** [comment]
> not important for 4.x

Maybe, but that's why it's labelled "low", or not? I think we should keep this open and fix this when we have time
