### ISSUE TITLE
Trying to delete a meeting throws an `Internal Server Error`

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-backend#953]
The payload I send:
```
backend_1           | DEBUG:openslides_backend.http.application:Request contains JSON: [{'action': 'meeting.delete', 'data': [{'id': 15}]}].
```

Further logs:
``` 
backend_1           | DEBUG:openslides_backend.http.views:Start dispatching action request.
backend_1           | DEBUG:openslides_backend.services.auth.adapter:Start request to authentication service with the following data: access_token: Host: localhost:8000
backend_1           | User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
backend_1           | Content-Length: 48
backend_1           | Accept: application/json, text/plain, */*
backend_1           | Accept-Encoding: gzip, deflate, br
backend_1           | Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
backend_1           | Authentication: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiIwNjI1Nzg4ODNjNzM2NDViMTExOTA5OWVlOTNkYjBhOSIsInVzZXJJZCI6MSwiaWF0IjoxNjMyNzQ4NDc1LCJleHAiOjE2MzI3NDkwNzV9.3ey2WLbdU3VdaxtWeMXdg3-skJjHzrSV68WU1LZS9Uk
backend_1           | Cache-Control: no-cache
backend_1           | Content-Type: application/json
backend_1           | Cookie: OpenSlidesCsrfToken=pe1e9PxzzwDhzgPfUrHzAs4VKRQ64s4axygD9305oZgOOugwCLVgZFbZUfW1VKlI; OpenSlidesSessionID=8c2ah1en713zrjpid7325zdz8nf100g6; refreshId=bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiIwNjI1Nzg4ODNjNzM2NDViMTExOTA5OWVlOTNkYjBhOSIsInVzZXJJZCI6MSwiaWF0IjoxNjMyNzM4ODA0LCJleHAiOjE2MzI4MjUyMDR9.w-HJHYZ26aLbDQpUSvpLYfe3F69_XJlUaEGAW5YwZp4
backend_1           | Dnt: 1
backend_1           | Origin: https://localhost:8000
backend_1           | Pragma: no-cache
backend_1           | Referer: https://localhost:8000/committees
backend_1           | Sec-Ch-Ua: "Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"
backend_1           | Sec-Ch-Ua-Mobile: ?0
backend_1           | Sec-Ch-Ua-Platform: "Linux"
backend_1           | Sec-Fetch-Dest: empty
backend_1           | Sec-Fetch-Mode: cors
backend_1           | Sec-Fetch-Site: same-origin
backend_1           | X-Csrftoken: pe1e9PxzzwDhzgPfUrHzAs4VKRQ64s4axygD9305oZgOOugwCLVgZFbZUfW1VKlI
backend_1           | X-Forwarded-For: 172.21.0.1
backend_1           | X-Forwarded-Proto: https
backend_1           | 
backend_1           | , cookie: bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiIwNjI1Nzg4ODNjNzM2NDViMTExOTA5OWVlOTNkYjBhOSIsInVzZXJJZCI6MSwiaWF0IjoxNjMyNzM4ODA0LCJleHAiOjE2MzI4MjUyMDR9.w-HJHYZ26aLbDQpUSvpLYfe3F69_XJlUaEGAW5YwZp4
backend_1           | DEBUG:openslides_backend.services.auth.adapter:Try to authenticate with
backend_1           | DEBUG:openslides_backend.services.auth.adapter:AccessToken: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiIwNjI1Nzg4ODNjNzM2NDViMTExOTA5OWVlOTNkYjBhOSIsInVzZXJJZCI6MSwiaWF0IjoxNjMyNzQ4NDc1LCJleHAiOjE2MzI3NDkwNzV9.3ey2WLbdU3VdaxtWeMXdg3-skJjHzrSV68WU1LZS9Uk
backend_1           | DEBUG:openslides_backend.services.auth.adapter:RefreshId: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiIwNjI1Nzg4ODNjNzM2NDViMTExOTA5OWVlOTNkYjBhOSIsInVzZXJJZCI6MSwiaWF0IjoxNjMyNzM4ODA0LCJleHAiOjE2MzI4MjUyMDR9.w-HJHYZ26aLbDQpUSvpLYfe3F69_XJlUaEGAW5YwZp4
backend_1           | DEBUG:openslides_backend.services.auth.adapter:Validator.verify
backend_1           | DEBUG:openslides_backend.services.auth.adapter:Validator.__assert_instance_of_encoded_jwt
backend_1           | DEBUG:openslides_backend.services.auth.adapter:Validator.__assert_instance_of_encoded_jwt
backend_1           | DEBUG:openslides_backend.services.auth.adapter:Validator.__verify_ticket
backend_1           | DEBUG:openslides_backend.services.auth.adapter:Validator.__get_jwt_from_bearer_jwt
backend_1           | DEBUG:openslides_backend.services.auth.adapter:Validator.__is_bearer
backend_1           | DEBUG:openslides_backend.services.auth.adapter:Validator.__get_jwt_from_bearer_jwt
backend_1           | DEBUG:openslides_backend.services.auth.adapter:Validator.__is_bearer
backend_1           | DEBUG:openslides_backend.services.auth.adapter:Validator.__decode
backend_1           | DEBUG:openslides_backend.services.auth.adapter:Validator.__decode
backend_1           | DEBUG:openslides_backend.http.views:User id is 1.
backend_1           | DEBUG:openslides_backend.shared.handlers.base_handler:Perform action meeting.delete.
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='meeting/15', mapped_fields={'meta_position', 'committee_id'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='user/1', mapped_fields={'organization_management_level', 'meta_position', 'committee_$2168_management_level'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='meeting/15', mapped_fields={'meta_position', 'user_ids'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='user/1', mapped_fields={'meta_position', 'comment_$'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='user/1', mapped_fields={'meta_position', 'number_$'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='user/1', mapped_fields={'structure_level_$', 'meta_position'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='user/1', mapped_fields={'meta_position', 'about_me_$'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='user/1', mapped_fields={'meta_position', 'vote_weight_$'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='meeting/15', mapped_fields={'motion_change_recommendation_ids', 'mediafile_ids', 'projector_countdown_ids', 'motion_comment_section_ids', 'meta_position', 'group_ids', 'assignment_ids', 'list_of_speakers_ids', 'motion_block_ids', 'poll_ids', 'assignment_candidate_ids', 'option_ids', 'motion_comment_ids', 'topic_ids', 'tag_ids', 'projector_message_ids', 'motion_workflow_ids', 'speaker_ids', 'all_projection_ids', 'motion_ids', 'projector_ids', 'motion_statute_paragraph_ids', 'motion_submitter_ids', 'motion_state_ids', 'meta_deleted', 'vote_ids', 'agenda_item_ids', 'chat_group_ids', 'motion_category_ids', 'personal_note_ids'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='meeting/15', mapped_fields={'meta_position', 'default_projector_$_id'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='meeting/15', mapped_fields={'meta_position', 'font_$_id'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='meeting/15', mapped_fields={'logo_$_id', 'meta_position'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'admin_group_for_meeting_id', 'default_group_for_meeting_id', 'meta_position', 'meta_deleted'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'meta_position', 'mediafile_access_group_ids'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'mediafile_inherited_access_group_ids', 'meta_position'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'meta_position', 'meeting_id'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'poll_ids', 'meta_position'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'meta_position', 'read_chat_group_ids'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'meta_position', 'read_comment_section_ids'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'meta_position', 'used_as_assignment_poll_default_id'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'used_as_motion_poll_default_id', 'meta_position'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'meta_position', 'used_as_poll_default_id'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'meta_position', 'user_ids'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'meta_position', 'write_chat_group_ids'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'write_comment_section_ids', 'meta_position'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/71', mapped_fields={'meta_position', 'meeting_id', 'user_ids'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/72', mapped_fields={'admin_group_for_meeting_id', 'default_group_for_meeting_id', 'meta_position', 'meta_deleted'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/72', mapped_fields={'meta_position', 'mediafile_access_group_ids'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/72', mapped_fields={'mediafile_inherited_access_group_ids', 'meta_position'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/72', mapped_fields={'meta_position', 'meeting_id'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/72', mapped_fields={'poll_ids', 'meta_position'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/72', mapped_fields={'meta_position', 'read_chat_group_ids'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/72', mapped_fields={'meta_position', 'read_comment_section_ids'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/72', mapped_fields={'meta_position', 'used_as_assignment_poll_default_id'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/72', mapped_fields={'used_as_motion_poll_default_id', 'meta_position'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/72', mapped_fields={'meta_position', 'used_as_poll_default_id'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/72', mapped_fields={'meta_position', 'user_ids'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/72', mapped_fields={'meta_position', 'meeting_id'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='user/1', mapped_fields={'group_$15_ids', 'meta_position'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET request to datastore with the following data: GetRequest(fqid='group/72', mapped_fields={'meta_position', 'meeting_id'}, position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
backend_1           | DEBUG:openslides_backend.services.datastore.adapter:Start GET_MANY request to datastore with the following data: GetManyRequest(requests=[GetManyRequestPart(collection='user', ids=[1], mapped_fields=['meta_position', 'group_$_ids'])], mapped_fields=[], position=None, get_deleted_models=<DeletedModelsBehaviour.NO_DELETED: 1>)
```

This is the error, I get 
```
backend_1           | [2021-09-27 13:14:43 +0000] [168] [ERROR] Error handling request /system/action/handle_request
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
backend_1           |     self.handle_request(listener, req, client, addr)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
backend_1           |     respiter = self.wsgi(environ, resp.start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 121, in __call__
backend_1           |     return self.wsgi_application(environ, start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 111, in wsgi_application
backend_1           |     response = self.dispatch_request(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 41, in dispatch_request
backend_1           |     return self.default_route(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 68, in default_route
backend_1           |     response_body, access_token = view_instance.dispatch(request)
backend_1           |   File "/app/openslides_backend/http/views.py", line 61, in dispatch
backend_1           |     response = handler.handle_request(request.json, user_id, is_atomic)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 98, in handle_request
backend_1           |     results = self.execute_write_requests(self.parse_actions, payload)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 131, in execute_write_requests
backend_1           |     write_requests, data = get_write_requests(*args)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 168, in parse_actions
backend_1           |     write_request, results = self.perform_action(element, relation_manager)
backend_1           |   File "/app/openslides_backend/action/action_handler.py", line 203, in perform_action
backend_1           |     write_request, results = action.perform(action_data, self.user_id)
backend_1           |   File "/app/openslides_backend/action/action.py", line 145, in perform
backend_1           |     instance = self.base_update_instance(instance)
backend_1           |   File "/app/openslides_backend/action/generics/delete.py", line 107, in base_update_instance
backend_1           |     self.execute_other_action(delete_action_class, delete_action_data)
backend_1           |   File "/app/openslides_backend/action/action.py", line 505, in execute_other_action
backend_1           |     write_request, action_results = action.perform(
backend_1           |   File "/app/openslides_backend/action/action.py", line 148, in perform
backend_1           |     self.write_requests.extend(relation_updates)
backend_1           |   File "/app/openslides_backend/action/action.py", line 267, in handle_relation_updates
backend_1           |     relation_updates = self.relation_manager.get_relation_updates(
backend_1           |   File "/app/openslides_backend/action/relations/relation_manager.py", line 76, in get_relation_updates
backend_1           |     result = handler.perform()
backend_1           |   File "/app/openslides_backend/action/relations/single_relation_handler.py", line 176, in perform
backend_1           |     result_template_field = self.prepare_result_template_field(result)
backend_1           |   File "/app/openslides_backend/action/relations/single_relation_handler.py", line 356, in prepare_result_template_field
backend_1           |     current_value.remove(replacement)
backend_1           | ValueError: list.remove(x): x not in list
```

The `meeting/15` model in the datastore:
```
{
  "id":15,
  "name":"Audit committee",
  "user_ids":[
    1
  ],
  "group_ids":[
    71,
    72,
    73,
    74,
    75
  ],
  "description":"Presentation and assembly system",
  "committee_id":2168,
  "meta_deleted":false,
  "welcome_text":"Space for your welcome text.",
  "applause_type":"applause-type-bar",
  "meta_position":138,
  "projector_ids":[
    16
  ],
  "users_pdf_url":"http://example.com:8000",
  "users_sort_by":"first_name",
  "welcome_title":"Welcome to OpenSlides",
  "admin_group_id":72,
  "applause_enable":false,
  "conference_show":false,
  "applause_timeout":5,
  "default_group_id":71,
  "enable_anonymous":false,
  "motion_state_ids":[
    211,
    212,
    213,
    214,
    215,
    216,
    217,
    218,
    219,
    220,
    221,
    222,
    223,
    224,
    225
  ],
  "motions_preamble":"The assembly may decide:",
  "users_email_body":"Dear {name},\n\n\nthis is your personal OpenSlides login:\n\n    {url}\n\n    username: {username}\n\n    password: {password}\n\n\n\nThis email was generated automatically.",
  "poll_countdown_id":30,
  "poll_default_type":"analog",
  "users_email_sender":"OpenSlides",
  "applause_max_amount":0,
  "applause_min_amount":1,
  "applause_show_level":false,
  "export_csv_encoding":"utf-8",
  "export_pdf_fontsize":10,
  "export_pdf_pagesize":"A4",
  "motion_workflow_ids":[
    29,
    30
  ],
  "motions_line_length":85,
  "motions_number_type":"per_category",
  "users_email_subject":"OpenSlides access data",
  "agenda_item_creation":"default_yes",
  "export_csv_separator":",",
  "motions_export_title":"Motions",
  "agenda_numeral_system":"arabic",
  "agenda_show_subtitles":false,
  "conference_open_video":false,
  "poll_couple_countdown":true,
  "users_pdf_welcometext":"[Place for your welcome and help text.]",
  "default_projector_$_id":[
    "agenda_all_items",
    "topics",
    "list_of_speakers",
    "current_list_of_speakers",
    "motion",
    "amendment",
    "motion_block",
    "assignment",
    "user",
    "mediafile",
    "projector_message",
    "projector_countdowns",
    "assignment_poll",
    "motion_poll",
    "poll"
  ],
  "reference_projector_id":16,
  "users_pdf_welcometitle":"Welcome to OpenSlides",
  "agenda_enable_numbering":true,
  "conference_auto_connect":false,
  "motions_default_sorting":"number",
  "motions_reason_required":false,
  "projector_countdown_ids":[
    29,
    30
  ],
  "assignments_export_title":"Elections",
  "motion_poll_default_type":"analog",
  "motions_statutes_enabled":false,
  "users_enable_vote_weight":false,
  "motions_amendments_prefix":"-",
  "motions_number_min_digits":1,
  "motions_number_with_blank":false,
  "conference_enable_helpdesk":false,
  "conference_los_restriction":false,
  "conference_open_microphone":false,
  "default_projector_$poll_id":16,
  "default_projector_$user_id":16,
  "motions_amendments_enabled":false,
  "users_enable_presence_view":false,
  "motions_default_workflow_id":29,
  "assignment_poll_default_type":"analog",
  "default_projector_$motion_id":16,
  "default_projector_$topics_id":16,
  "is_active_in_organization_id":1,
  "motions_amendments_text_mode":"paragraph",
  "users_allow_self_set_present":false,
  "list_of_speakers_countdown_id":29,
  "motions_supporters_min_amount":0,
  "poll_default_100_percent_base":"YNA",
  "motions_default_line_numbering":"outside",
  "motions_show_referring_motions":true,
  "motions_show_sequential_number":true,
  "default_projector_$amendment_id":16,
  "default_projector_$mediafile_id":16,
  "export_pdf_pagenumber_alignment":"center",
  "motion_poll_ballot_paper_number":8,
  "motions_amendments_in_main_list":true,
  "default_projector_$assignment_id":16,
  "motions_amendments_of_amendments":false,
  "motions_enable_text_on_projector":true,
  "motions_recommendation_text_mode":"diff",
  "projector_countdown_default_time":60,
  "projector_countdown_warning_time":0,
  "default_projector_$motion_poll_id":16,
  "list_of_speakers_couple_countdown":true,
  "list_of_speakers_initially_closed":false,
  "default_projector_$motion_block_id":16,
  "motion_poll_ballot_paper_selection":"CUSTOM_NUMBER",
  "motions_enable_reason_on_projector":true,
  "agenda_new_items_default_visibility":"internal",
  "assignment_poll_ballot_paper_number":8,
  "list_of_speakers_present_users_only":false,
  "motions_enable_sidebox_on_projector":false,
  "motion_poll_default_100_percent_base":"YNA",
  "motions_export_follow_recommendation":false,
  "conference_auto_connect_next_speakers":0,
  "default_projector_$assignment_poll_id":16,
  "motions_default_amendment_workflow_id":29,
  "assignment_poll_ballot_paper_selection":"CUSTOM_NUMBER",
  "default_projector_$agenda_all_items_id":16,
  "default_projector_$list_of_speakers_id":16,
  "motions_amendments_multiple_paragraphs":true,
  "agenda_show_internal_items_on_projector":true,
  "default_projector_$projector_message_id":16,
  "motions_export_submitter_recommendation":false,
  "assignment_poll_default_100_percent_base":"valid",
  "list_of_speakers_show_first_contribution":false,
  "assignment_poll_sort_poll_result_by_votes":true,
  "list_of_speakers_amount_last_on_projector":0,
  "list_of_speakers_amount_next_on_projector":-1,
  "list_of_speakers_enable_pro_contra_speech":false,
  "default_projector_$projector_countdowns_id":16,
  "list_of_speakers_can_set_contribution_self":false,
  "list_of_speakers_speaker_note_for_everyone":false,
  "motions_enable_recommendation_on_projector":true,
  "motions_default_statute_amendment_workflow_id":29,
  "default_projector_$current_list_of_speakers_id":16,
  "list_of_speakers_enable_point_of_order_speakers":false,
  "list_of_speakers_show_amount_of_speakers_on_slide":true,
  "assignment_poll_add_candidates_to_list_of_speakers":true
}
```

**Comment by GabrielInTheWorld** [comment]
I don't know, why this error occurs. Maybe you can tell me.

**Comment by jsangmeister** [comment]
This hints at a critical bug somewhere in the backend code. Can you provide the full datastore content (or at least all models referenced in the meeting) and how you created the meeting (clone/normal create/example data/...)?
